# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps
    if apps.ready:
        from .backport_data_backup import Command
        from .backport_data_restore import Command
        from .create_shop_jobs import Command
        from .create_test_quote_data import Command
        from .set_paid_flag_jobs import Command
        from .test_claude_chat import Command
        from .test_diff_engine import Command
        from .test_gemini_chat import Command
        from .test_quote_import import Command
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "Command",
]
