# Generated by Django 5.2 on 2025-07-01 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0013_populate_unit_revenue_from_existing_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="retail_rate",
        ),
    ]
