# Generated by Django 5.2 on 2025-11-01 17:33

from django.db import migrations, models
from django.db.models import Count, F, Q


def populate_active_source_purchase_order_line(apps, schema_editor):
    Stock = apps.get_model("purchasing", "Stock")

    active_items = Stock.objects.filter(
        is_active=True, source_purchase_order_line__isnull=False
    )
    duplicates = (
        active_items.values("source_purchase_order_line_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        sample = ", ".join(
            str(row["source_purchase_order_line_id"]) for row in duplicates[:5]
        )
        raise RuntimeError(
            "Active stock duplicates detected for purchase order lines; "
            "resolve duplicates before applying migration. "
            f"Example IDs: {sample}"
        )

    active_items.update(
        active_source_purchase_order_line_id=F("source_purchase_order_line_id")
    )
    Stock.objects.filter(
        Q(is_active=False) | Q(source_purchase_order_line__isnull=True)
    ).update(active_source_purchase_order_line_id=None)


def reset_active_source_purchase_order_line(apps, schema_editor):
    Stock = apps.get_model("purchasing", "Stock")
    Stock.objects.update(active_source_purchase_order_line_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0051_fix_costset_summary_default"),
        ("purchasing", "0014_remove_retail_rate_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="active_source_purchase_order_line_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Denormalized pointer used to enforce single active stock item per purchase order line.",
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_active_source_purchase_order_line,
            reset_active_source_purchase_order_line,
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("active_source_purchase_order_line_id",),
                name="unique_active_stock_per_po_line",
            ),
        ),
    ]
