# Generated by Django 5.2 on 2025-10-30 14:49

from django.db import migrations, models


def merge_duplicate_stock(apps, schema_editor):
    from apps.purchasing.stock_cleanup import consolidate_duplicate_stock

    consolidate_duplicate_stock(dry_run=False)


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0051_fix_costset_summary_default"),
        ("purchasing", "0014_remove_retail_rate_field"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_stock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True), ("source_purchase_order_line__isnull", False)
                ),
                fields=("source_purchase_order_line",),
                name="unique_active_stock_per_po_line",
            ),
        ),
    ]
