# Generated by Django 5.2 on 2025-12-01 20:11

from django.db import migrations, models


def fix_empty_source(apps, schema_editor):
    """Set empty source values to 'product_catalog'."""
    Stock = apps.get_model("purchasing", "Stock")
    Stock.objects.filter(source="").update(source="product_catalog")


def reverse_fix_empty_source(apps, schema_editor):
    """Reverse: set product_catalog back to empty (for rollback)."""
    Stock = apps.get_model("purchasing", "Stock")
    Stock.objects.filter(source="product_catalog").update(source="")


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0015_stock_active_source_purchase_order_line_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="source",
            field=models.CharField(
                choices=[
                    ("purchase_order", "Purchase Order Receipt"),
                    ("split_from_stock", "Split/Offcut from Stock"),
                    ("manual", "Manual Adjustment/Stocktake"),
                    ("product_catalog", "Product Catalog"),
                ],
                help_text="Origin of this stock item",
                max_length=50,
            ),
        ),
        migrations.RunPython(fix_empty_source, reverse_fix_empty_source),
    ]
