# Generated by Django 5.2 on 2025-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0016_add_product_catalog_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the stock item", null=True
            ),
        ),
    ]
