# Generated by Django 5.2 on 2025-12-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0016_add_product_catalog_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="notes",
        ),
    ]
