# Generated by Django 5.2 on 2025-12-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0017_remove_stock_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="xero_line_item_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Xero's unique identifier for this line item (from line_item_id)",
                null=True,
            ),
        ),
    ]
