# Generated by Django 5.2 on 2025-12-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_supplierpickupaddress"),
        ("purchasing", "0021_clean_po_line_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="pickup_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivery/pickup address for this purchase order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="client.supplierpickupaddress",
            ),
        ),
    ]
