# Generated by Django 5.2 on 2025-12-20 20:09
"""
Migration to deduplicate stock item_codes.

For each duplicate item_code:
1. Keep one "keeper" (prefer one with xero_id, then first active)
2. Merge duplicates into keeper (move all references, then delete)
"""

from django.db import migrations
from django.db.models import Count


def dedupe_stock_item_codes(apps, schema_editor):
    from apps.purchasing.services.stock_service import merge_stock_into

    Stock = apps.get_model("purchasing", "Stock")

    duplicates = (
        Stock.objects.exclude(item_code__isnull=True)
        .exclude(item_code="")
        .values("item_code")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        item_code = dup["item_code"]
        stocks = list(Stock.objects.filter(item_code=item_code).order_by("id"))

        # Find keeper: prefer xero_id, then active, then first
        keeper = next((s for s in stocks if s.xero_id), None)
        if not keeper:
            keeper = next((s for s in stocks if s.is_active), stocks[0])

        # Merge all duplicates into keeper
        for stock in stocks:
            if stock.id != keeper.id:
                merge_stock_into(stock.id, keeper.id)


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0025_add_xero_last_synced_to_stock"),
    ]

    operations = [
        migrations.RunPython(dedupe_stock_item_codes, migrations.RunPython.noop),
    ]
