# Generated by Django 5.2 on 2025-12-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0023_dedupe_stock_item_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderline",
            name="item_code",
            field=models.CharField(
                blank=True,
                help_text="Internal item code for Xero integration",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="item_code",
            field=models.CharField(
                blank=True,
                help_text="Xero Item Code",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
