# Generated by Django 5.2 on 2025-12-25 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0024_stock_item_code_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="When this item was last synced with Xero",
                null=True,
            ),
        ),
    ]
