# Generated by Django 5.2 on 2026-01-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0024_stock_item_code_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True,
                help_text="When this item was last synced with Xero (None = never synced)",
                null=True,
            ),
        ),
    ]
