# Generated by Django 6.0.1 on 2026-01-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0026_remove_xero_last_synced_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                help_text="Staff member who created this purchase order",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
