# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .core import (
            JobAgingFinancialDataSerializer,
            JobAgingJobDataSerializer,
            JobAgingQuerySerializer,
            JobAgingResponseSerializer,
            JobAgingTimingDataSerializer,
            KPICalendarDataSerializer,
            KPICalendarErrorResponseSerializer,
            KPIDayDataSerializer,
            KPIDetailsSerializer,
            KPIJobBreakdownSerializer,
            KPIMonthlyTotalsSerializer,
            KPIProfitBreakdownSerializer,
            KPIThresholdsSerializer,
            StaffPerformanceErrorResponseSerializer,
            StaffPerformanceJobBreakdownSerializer,
            StaffPerformancePeriodSummarySerializer,
            StaffPerformanceResponseSerializer,
            StaffPerformanceStaffDataSerializer,
            StaffPerformanceTeamAveragesSerializer,
            StandardErrorSerializer,
        )
        from .payroll_reconciliation_serializers import (
            PayrollDateRangeResponseSerializer,
            PayrollGrandTotalsSerializer,
            PayrollHeatmapRowSerializer,
            PayrollHeatmapSerializer,
            PayrollReconciliationResponseSerializer,
            PayrollStaffSummarySerializer,
            PayrollStaffWeekSerializer,
            PayrollWeekSerializer,
            PayrollWeekTotalsSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "JobAgingFinancialDataSerializer",
    "JobAgingJobDataSerializer",
    "JobAgingQuerySerializer",
    "JobAgingResponseSerializer",
    "JobAgingTimingDataSerializer",
    "KPICalendarDataSerializer",
    "KPICalendarErrorResponseSerializer",
    "KPIDayDataSerializer",
    "KPIDetailsSerializer",
    "KPIJobBreakdownSerializer",
    "KPIMonthlyTotalsSerializer",
    "KPIProfitBreakdownSerializer",
    "KPIThresholdsSerializer",
    "PayrollDateRangeResponseSerializer",
    "PayrollGrandTotalsSerializer",
    "PayrollHeatmapRowSerializer",
    "PayrollHeatmapSerializer",
    "PayrollReconciliationResponseSerializer",
    "PayrollStaffSummarySerializer",
    "PayrollStaffWeekSerializer",
    "PayrollWeekSerializer",
    "PayrollWeekTotalsSerializer",
    "StaffPerformanceErrorResponseSerializer",
    "StaffPerformanceJobBreakdownSerializer",
    "StaffPerformancePeriodSummarySerializer",
    "StaffPerformanceResponseSerializer",
    "StaffPerformanceStaffDataSerializer",
    "StaffPerformanceTeamAveragesSerializer",
    "StandardErrorSerializer",
]
