# Generated by Django 5.2 on 2025-07-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_staff_groups_alter_staff_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="date_left",
            field=models.DateField(
                blank=True,
                help_text="Date staff member left employment (null for current employees)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="date_left",
            field=models.DateField(
                blank=True,
                help_text="Date staff member left employment (null for current employees)",
                null=True,
            ),
        ),
    ]
