# Generated by Django 5.2 on 2025-07-30 23:59

from django.db import migrations
from django.utils import timezone


def migrate_inactive_staff(apps, schema_editor):
    Staff = apps.get_model("accounts", "Staff")
    today = timezone.now().date()

    # Set date_left to today for all currently inactive staff
    Staff.objects.filter(is_active=False).update(date_left=today)


def reverse_migration(apps, schema_editor):
    Staff = apps.get_model("accounts", "Staff")

    # Set is_active=False for staff with date_left
    Staff.objects.filter(date_left__isnull=False).update(is_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_historicalstaff_date_left_staff_date_left"),
    ]

    operations = [
        migrations.RunPython(migrate_inactive_staff, reverse_migration),
    ]
