# Generated by Django 5.2 on 2025-07-31 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_auto_20250730_2359"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstaff",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_active",
        ),
    ]
