# Generated by Django 5.2 on 2025-08-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_historicalstaff_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="xero_user_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="xero_user_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
