# Generated by Django 5.2 on 2025-12-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_historicalstaff_xero_user_id_staff_xero_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalstaff",
            old_name="is_staff",
            new_name="is_office_staff",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="is_staff",
            new_name="is_office_staff",
        ),
    ]
