# Generated by Django 5.2 on 2025-12-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_historicalstaff_xero_user_id_staff_xero_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstaff",
            name="ims_payroll_id",
        ),
        migrations.RemoveField(
            model_name="historicalstaff",
            name="raw_ims_data",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="ims_payroll_id",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="raw_ims_data",
        ),
    ]
