# Generated by Django 5.2 on 2025-12-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0010_rename_is_staff_historicalstaff_is_office_staff_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstaff",
            name="ims_payroll_id",
        ),
        migrations.RemoveField(
            model_name="historicalstaff",
            name="raw_ims_data",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="ims_payroll_id",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="raw_ims_data",
        ),
    ]
