# Generated by Django 6.0.1 on 2026-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_base_wage_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="base_wage_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Actual hourly pay rate. wage_rate is auto-computed with leave loading.",
                max_digits=10,
            ),
        ),
    ]
