# This file is autogenerated by update_init.py script

from .apps import JobConfig
from .enums import MetalType, SpeedQualityTradeoff
from .helpers import get_job_folder_path

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .diff import DiffResult, apply_diff, diff_costset
        from .mixins import JobLookupMixin, JobNumberLookupMixin
        from .permissions import IsOfficeStaff, IsStaffUser
        from .scheduler_jobs import set_paid_flag_jobs
        from .utils import get_active_jobs, get_jobs_data
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "DiffResult",
    "IsOfficeStaff",
    "IsStaffUser",
    "JobConfig",
    "JobLookupMixin",
    "JobNumberLookupMixin",
    "MetalType",
    "SpeedQualityTradeoff",
    "apply_diff",
    "diff_costset",
    "get_active_jobs",
    "get_job_folder_path",
    "get_jobs_data",
    "set_paid_flag_jobs",
]
