# This file is autogenerated by update_init.py script

from .job_aging_view import JobAgingAPIView
from .kpi_view import KPICalendarAPIView, KPICalendarTemplateView
from .sales_forecast_view import (
    SalesForecastAPIView,
    SalesForecastMonthDetailAPIView,
    SalesForecastTemplateView,
)
from .staff_performance_views import (
    StaffPerformanceDetailAPIView,
    StaffPerformanceSummaryAPIView,
    StaffPerformanceTemplateView,
)

__all__ = [
    "JobAgingAPIView",
    "KPICalendarAPIView",
    "KPICalendarTemplateView",
    "SalesForecastAPIView",
    "SalesForecastMonthDetailAPIView",
    "SalesForecastTemplateView",
    "StaffPerformanceDetailAPIView",
    "StaffPerformanceSummaryAPIView",
    "StaffPerformanceTemplateView",
]
