# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps
    if apps.ready:
        from .job_aging_view import JobAgingAPIView
        from .kpi_view import KPICalendarTemplateView, KPICalendarAPIView
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "JobAgingAPIView",
    "KPICalendarAPIView",
    "KPICalendarTemplateView",
]
