# This file is autogenerated by update_init.py script

from .job_aging_view import JobAgingAPIView
from .kpi_view import KPICalendarAPIView, KPICalendarTemplateView
from .staff_performance_views import (
    StaffPerformanceDetailAPIView,
    StaffPerformanceSummaryAPIView,
    StaffPerformanceTemplateView,
)

__all__ = [
    "JobAgingAPIView",
    "KPICalendarAPIView",
    "KPICalendarTemplateView",
    "StaffPerformanceDetailAPIView",
    "StaffPerformanceSummaryAPIView",
    "StaffPerformanceTemplateView",
]
