# Generated by Django 5.2 on 2025-07-07 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0002_alter_timeentry_job_pricing_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeEntry",
        ),
    ]
