# Generated by Django 5.2 on 2025-11-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("timesheet", "0003_delete_timeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroPayRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_run_id", models.UUIDField(unique=True)),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("pay_run_status", models.CharField(max_length=32)),
                (
                    "pay_run_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period_start_date", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["period_start_date"],
                        name="timesheet_x_period__9714bc_idx",
                    ),
                    models.Index(
                        fields=["pay_run_status"], name="timesheet_x_pay_run_fa996e_idx"
                    ),
                ],
            },
        ),
    ]
