# Generated by Django 5.2 on 2025-12-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0005_xero_payrun"),
    ]

    operations = [
        migrations.DeleteModel(
            name="XeroPayRun",
        ),
    ]
