# Generated by Django 5.2 on 2025-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_populate_merge_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_supplier",
            field=models.BooleanField(default=False),
        ),
    ]
