# Generated by Django 5.2.5 on 2025-08-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_client_is_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
