# Generated by Django 5.2 on 2025-10-14 20:48

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_empty_name_contacts(apps, schema_editor):
    """
    Delete all ClientContact records where name is empty or whitespace.
    These contacts are pointless - a contact must have a name.
    """
    ClientContact = apps.get_model("client", "ClientContact")

    # Find contacts with empty/whitespace names
    empty_name_contacts = ClientContact.objects.filter(
        name__in=["", None]
    ) | ClientContact.objects.filter(name__regex=r"^\s*$")

    count = empty_name_contacts.count()

    if count > 0:
        logger.info(
            f"Deleting {count} ClientContact records with empty names "
            "(contacts without names are pointless)"
        )
        deleted_count, _ = empty_name_contacts.delete()
        logger.info(f"Successfully deleted {deleted_count} empty-name contacts")
    else:
        logger.info("No empty-name ClientContact records found - database is clean")


def reverse_migration(apps, schema_editor):
    """
    This migration cannot be reversed - we've deleted useless data.
    """
    logger.warning(
        "Cannot reverse deletion of empty-name ClientContact records "
        "(no useful data to restore)"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_alter_client_name"),
    ]

    operations = [
        migrations.RunPython(delete_empty_name_contacts, reverse_migration),
    ]
