# Generated by Django 5.2 on 2025-10-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_merge_duplicate_contacts"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientcontact",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="unique_client_contact_name"
            ),
        ),
    ]
