# Generated by Django 5.2 on 2025-11-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0009_clientcontact_unique_client_contact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontact",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Soft delete flag - inactive contacts are hidden from normal queries",
            ),
        ),
    ]
