# Generated by Django 5.1.4 on 2025-12-16
"""
Convert empty strings to NULL for nullable fields in ClientContact.

This migration fixes data that was incorrectly saved with empty strings
instead of NULL for optional fields (email, phone, position, notes).

The root cause was:
1. reprocess_xero.py line 297: email = person.get("_email_address", "")
2. Migration 0017_migrate_contact_data.py: phone=job.contact_phone or ""
"""

from django.db import migrations


def convert_empty_strings_to_null(apps, schema_editor):
    """Convert empty string values to NULL for nullable fields."""
    ClientContact = apps.get_model("client", "ClientContact")

    # Fields that should be NULL instead of empty string
    nullable_fields = ["email", "phone", "position", "notes"]

    for field in nullable_fields:
        updated = ClientContact.objects.filter(**{field: ""}).update(**{field: None})
        if updated > 0:
            print(f"  Converted {updated} empty {field} fields to NULL")


def reverse_null_to_empty_strings(apps, schema_editor):
    """Reverse: convert NULL values back to empty strings (not recommended)."""
    ClientContact = apps.get_model("client", "ClientContact")

    nullable_fields = ["email", "phone", "position", "notes"]

    for field in nullable_fields:
        updated = ClientContact.objects.filter(**{f"{field}__isnull": True}).update(
            **{field: ""}
        )
        if updated > 0:
            print(f"  Converted {updated} NULL {field} fields to empty strings")


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_add_is_active_to_clientcontact"),
    ]

    operations = [
        migrations.RunPython(
            convert_empty_strings_to_null,
            reverse_null_to_empty_strings,
        ),
    ]
