# Generated by Django 5.2 on 2025-12-18 03:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_convert_empty_strings_to_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPickupAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this address (e.g., 'Main Warehouse', 'City Branch')",
                        max_length=255,
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street address including unit/suite number",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(help_text="City or suburb", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal or ZIP code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Australia", help_text="Country name", max_length=100
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the primary pickup address for the supplier",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes (e.g., opening hours, access instructions)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete flag - inactive addresses are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The supplier this pickup address belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_addresses",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Pickup Address",
                "verbose_name_plural": "Supplier Pickup Addresses",
                "db_table": "client_supplier_pickup_address",
                "ordering": ["-is_primary", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "name"),
                        name="unique_supplier_pickup_address_name",
                    )
                ],
            },
        ),
    ]
