# Generated by Django 5.2 on 2025-12-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_supplierpickupaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpickupaddress",
            name="google_place_id",
            field=models.CharField(
                blank=True,
                help_text="Google Place ID for this address",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplierpickupaddress",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplierpickupaddress",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplierpickupaddress",
            name="country",
            field=models.CharField(
                default="New Zealand", help_text="Country name", max_length=100
            ),
        ),
    ]
