# Generated by Django 5.2 on 2025-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_add_google_fields_to_pickup_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpickupaddress",
            name="suburb",
            field=models.CharField(
                blank=True,
                help_text="Suburb or neighbourhood (e.g., Thorndon, Northcote Point)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplierpickupaddress",
            name="city",
            field=models.CharField(
                help_text="City (e.g., Wellington, Auckland)", max_length=100
            ),
        ),
    ]
