# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .chat_file_service import ChatFileService
        from .data_quality_report import ArchivedJobsComplianceService
        from .delivery_docket_service import generate_delivery_docket
        from .delta_checksum import (
            ChecksumInput,
            compute_job_delta_checksum,
            normalise_value,
        )
        from .file_service import (
            create_thumbnail,
            get_thumbnail_folder,
            sync_job_folder,
        )
        from .gemini_chat_service import GeminiChatService
        from .import_quote_service import (
            QuoteImportError,
            QuoteImportResult,
            import_quote_from_drafts,
            import_quote_from_file,
            preview_quote_import,
            preview_quote_import_from_drafts,
            serialize_draft_lines,
            serialize_validation_report,
        )
        from .job_rest_service import (
            DeltaValidationError,
            JobDeltaPayload,
            JobRestService,
            PreconditionFailed,
        )
        from .job_service import (
            JobStaffService,
            archive_complete_jobs,
            get_job_total_value,
            get_paid_complete_jobs,
            recalculate_job_invoicing_state,
        )
        from .kanban_categorization_service import (
            KanbanCategorizationService,
            KanbanColumn,
        )
        from .kanban_service import KanbanService
        from .mcp_chat_service import MCPChatService
        from .month_end_service import MonthEndService
        from .paid_flag_service import PaidFlagResult, PaidFlagService
        from .quote_mode_controller import QuoteModeController
        from .quote_sync_service import apply_quote, link_quote_sheet, preview_quote
        from .workshop_pdf_service import (
            add_delivery_docket_details_table,
            add_handover_section,
            add_logo,
            add_materials_used_table,
            add_time_used_table,
            add_title,
            add_workshop_details_table,
            convert_html_to_reportlab,
            create_delivery_docket_main_document,
            create_delivery_docket_pdf,
            create_image_document,
            create_workshop_main_document,
            create_workshop_pdf,
            draw_table_with_page_breaks,
            get_image_dimensions,
            get_pdf_file_paths,
            get_time_breakdown,
            get_workshop_hours,
            merge_pdfs,
            process_attachments,
            wait_until_file_ready,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "ArchivedJobsComplianceService",
    "ChatFileService",
    "ChecksumInput",
    "DeltaValidationError",
    "GeminiChatService",
    "JobDeltaPayload",
    "JobRestService",
    "JobStaffService",
    "KanbanCategorizationService",
    "KanbanColumn",
    "KanbanService",
    "MCPChatService",
    "MonthEndService",
    "PaidFlagResult",
    "PaidFlagService",
    "PreconditionFailed",
    "QuoteImportError",
    "QuoteImportResult",
    "QuoteModeController",
    "add_delivery_docket_details_table",
    "add_handover_section",
    "add_logo",
    "add_materials_used_table",
    "add_time_used_table",
    "add_title",
    "add_workshop_details_table",
    "apply_quote",
    "archive_complete_jobs",
    "compute_job_delta_checksum",
    "convert_html_to_reportlab",
    "create_delivery_docket_main_document",
    "create_delivery_docket_pdf",
    "create_image_document",
    "create_thumbnail",
    "create_workshop_main_document",
    "create_workshop_pdf",
    "draw_table_with_page_breaks",
    "generate_delivery_docket",
    "get_image_dimensions",
    "get_job_total_value",
    "get_paid_complete_jobs",
    "get_pdf_file_paths",
    "get_thumbnail_folder",
    "get_time_breakdown",
    "get_workshop_hours",
    "import_quote_from_drafts",
    "import_quote_from_file",
    "link_quote_sheet",
    "merge_pdfs",
    "normalise_value",
    "preview_quote",
    "preview_quote_import",
    "preview_quote_import_from_drafts",
    "process_attachments",
    "recalculate_job_invoicing_state",
    "serialize_draft_lines",
    "serialize_validation_report",
    "sync_job_folder",
    "wait_until_file_ready",
]
