# This file is autogenerated by update_init.py script

from .apps import PurchasingConfig
from .exceptions import PreconditionFailedError

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .etag import generate_po_etag, normalize_etag
        from .forms import PurchaseOrderForm, PurchaseOrderLineForm
        from .models import (
            PurchaseOrder,
            PurchaseOrderLine,
            PurchaseOrderSupplierQuote,
            Stock,
        )
        from .serializers import (
            AllJobsResponseSerializer,
            AllocationDeleteResponseSerializer,
            AllocationDeleteSerializer,
            AllocationDetailsResponseSerializer,
            AllocationItemSerializer,
            DeliveryReceiptAllocationSerializer,
            DeliveryReceiptLineSerializer,
            DeliveryReceiptResponseSerializer,
            DeliveryReceiptSerializer,
            JobForPurchasingSerializer,
            ProductMappingListResponseSerializer,
            ProductMappingSerializer,
            ProductMappingValidateResponseSerializer,
            ProductMappingValidateSerializer,
            PurchaseOrderAllocationsResponseSerializer,
            PurchaseOrderCreateResponseSerializer,
            PurchaseOrderCreateSerializer,
            PurchaseOrderDetailSerializer,
            PurchaseOrderEmailResponseSerializer,
            PurchaseOrderEmailSerializer,
            PurchaseOrderLineCreateSerializer,
            PurchaseOrderLineSerializer,
            PurchaseOrderLineUpdateSerializer,
            PurchaseOrderListSerializer,
            PurchaseOrderPDFResponseSerializer,
            PurchaseOrderUpdateResponseSerializer,
            PurchaseOrderUpdateSerializer,
            PurchasingErrorResponseSerializer,
            PurchasingJobsResponseSerializer,
            StockConsumeResponseSerializer,
            StockConsumeSerializer,
            StockCreateResponseSerializer,
            StockCreateSerializer,
            StockDeactivateResponseSerializer,
            StockItemSerializer,
            StockListSerializer,
            SupplierPriceStatusItemSerializer,
            SupplierPriceStatusResponseSerializer,
            XeroItemListResponseSerializer,
            XeroItemSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

# EXCLUDED IMPORTS - These contain problematic dependencies that cause circular imports
# Import these directly where needed using:
# from .admin import PurchaseOrderAdmin
# from .admin import PurchaseOrderLineAdmin
#

__all__ = [
    "AllJobsResponseSerializer",
    "AllocationDeleteResponseSerializer",
    "AllocationDeleteSerializer",
    "AllocationDetailsResponseSerializer",
    "AllocationItemSerializer",
    "DeliveryReceiptAllocationSerializer",
    "DeliveryReceiptLineSerializer",
    "DeliveryReceiptResponseSerializer",
    "DeliveryReceiptSerializer",
    "JobForPurchasingSerializer",
    "PreconditionFailedError",
    "ProductMappingListResponseSerializer",
    "ProductMappingSerializer",
    "ProductMappingValidateResponseSerializer",
    "ProductMappingValidateSerializer",
    "PurchaseOrder",
    "PurchaseOrderAllocationsResponseSerializer",
    "PurchaseOrderCreateResponseSerializer",
    "PurchaseOrderCreateSerializer",
    "PurchaseOrderDetailSerializer",
    "PurchaseOrderEmailResponseSerializer",
    "PurchaseOrderEmailSerializer",
    "PurchaseOrderForm",
    "PurchaseOrderLine",
    "PurchaseOrderLineCreateSerializer",
    "PurchaseOrderLineForm",
    "PurchaseOrderLineSerializer",
    "PurchaseOrderLineUpdateSerializer",
    "PurchaseOrderListSerializer",
    "PurchaseOrderPDFResponseSerializer",
    "PurchaseOrderSupplierQuote",
    "PurchaseOrderUpdateResponseSerializer",
    "PurchaseOrderUpdateSerializer",
    "PurchasingConfig",
    "PurchasingErrorResponseSerializer",
    "PurchasingJobsResponseSerializer",
    "Stock",
    "StockConsumeResponseSerializer",
    "StockConsumeSerializer",
    "StockCreateResponseSerializer",
    "StockCreateSerializer",
    "StockDeactivateResponseSerializer",
    "StockItemSerializer",
    "StockListSerializer",
    "SupplierPriceStatusItemSerializer",
    "SupplierPriceStatusResponseSerializer",
    "XeroItemListResponseSerializer",
    "XeroItemSerializer",
    "generate_po_etag",
    "normalize_etag",
]
