# This file is autogenerated by update_init.py script

from .apps import PurchasingConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .forms import PurchaseOrderForm, PurchaseOrderLineForm
        from .models import (
            PurchaseOrder,
            PurchaseOrderLine,
            PurchaseOrderSupplierQuote,
            Stock,
        )
        from .serializers import (
            AllJobsResponseSerializer,
            AllocationItemSerializer,
            DeliveryReceiptAllocationSerializer,
            DeliveryReceiptLineSerializer,
            DeliveryReceiptRequestSerializer,
            DeliveryReceiptResponseSerializer,
            JobForPurchasingSerializer,
            PurchaseOrderAllocationsResponseSerializer,
            PurchaseOrderCreateResponseSerializer,
            PurchaseOrderCreateSerializer,
            PurchaseOrderDetailSerializer,
            PurchaseOrderEmailRequestSerializer,
            PurchaseOrderEmailResponseSerializer,
            PurchaseOrderLineCreateSerializer,
            PurchaseOrderLineSerializer,
            PurchaseOrderLineUpdateSerializer,
            PurchaseOrderListSerializer,
            PurchaseOrderPDFResponseSerializer,
            PurchaseOrderUpdateResponseSerializer,
            PurchaseOrderUpdateSerializer,
            PurchasingErrorResponseSerializer,
            PurchasingJobsResponseSerializer,
            StockConsumeRequestSerializer,
            StockConsumeResponseSerializer,
            StockCreateResponseSerializer,
            StockCreateSerializer,
            StockDeactivateResponseSerializer,
            StockItemSerializer,
            StockListSerializer,
            XeroItemListResponseSerializer,
            XeroItemSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

# EXCLUDED IMPORTS - These contain problematic dependencies that cause circular imports
# Import these directly where needed using:
# from .admin import PurchaseOrderAdmin
# from .admin import PurchaseOrderLineAdmin
#

__all__ = [
    "AllJobsResponseSerializer",
    "AllocationItemSerializer",
    "DeliveryReceiptAllocationSerializer",
    "DeliveryReceiptLineSerializer",
    "DeliveryReceiptRequestSerializer",
    "DeliveryReceiptResponseSerializer",
    "JobForPurchasingSerializer",
    "PurchaseOrder",
    "PurchaseOrderAllocationsResponseSerializer",
    "PurchaseOrderCreateResponseSerializer",
    "PurchaseOrderCreateSerializer",
    "PurchaseOrderDetailSerializer",
    "PurchaseOrderEmailRequestSerializer",
    "PurchaseOrderEmailResponseSerializer",
    "PurchaseOrderForm",
    "PurchaseOrderLine",
    "PurchaseOrderLineCreateSerializer",
    "PurchaseOrderLineForm",
    "PurchaseOrderLineSerializer",
    "PurchaseOrderLineUpdateSerializer",
    "PurchaseOrderListSerializer",
    "PurchaseOrderPDFResponseSerializer",
    "PurchaseOrderSupplierQuote",
    "PurchaseOrderUpdateResponseSerializer",
    "PurchaseOrderUpdateSerializer",
    "PurchasingConfig",
    "PurchasingErrorResponseSerializer",
    "PurchasingJobsResponseSerializer",
    "Stock",
    "StockConsumeRequestSerializer",
    "StockConsumeResponseSerializer",
    "StockCreateResponseSerializer",
    "StockCreateSerializer",
    "StockDeactivateResponseSerializer",
    "StockItemSerializer",
    "StockListSerializer",
    "XeroItemListResponseSerializer",
    "XeroItemSerializer",
]
