# This file is autogenerated by update_init.py script

from .apps import ClientConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .forms import ClientForm
        from .models import Client, ClientContact, Supplier
        from .serializers import (
            ClientContactCreateRequestSerializer,
            ClientContactCreateResponseSerializer,
            ClientContactListResponseSerializer,
            ClientContactResponseSerializer,
            ClientContactResultSerializer,
            ClientContactSerializer,
            ClientCreateRequestSerializer,
            ClientCreateResponseSerializer,
            ClientDetailResponseSerializer,
            ClientDuplicateErrorResponseSerializer,
            ClientErrorResponseSerializer,
            ClientJobHeaderSerializer,
            ClientJobsResponseSerializer,
            ClientListResponseSerializer,
            ClientNameOnlySerializer,
            ClientSearchResponseSerializer,
            ClientSearchResultSerializer,
            ClientSerializer,
            ClientUpdateRequestSerializer,
            ClientUpdateResponseSerializer,
            JobContactResponseSerializer,
            JobContactUpdateRequestSerializer,
            StandardErrorSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "Client",
    "ClientConfig",
    "ClientContact",
    "ClientContactCreateRequestSerializer",
    "ClientContactCreateResponseSerializer",
    "ClientContactListResponseSerializer",
    "ClientContactResponseSerializer",
    "ClientContactResultSerializer",
    "ClientContactSerializer",
    "ClientCreateRequestSerializer",
    "ClientCreateResponseSerializer",
    "ClientDetailResponseSerializer",
    "ClientDuplicateErrorResponseSerializer",
    "ClientErrorResponseSerializer",
    "ClientForm",
    "ClientJobHeaderSerializer",
    "ClientJobsResponseSerializer",
    "ClientListResponseSerializer",
    "ClientNameOnlySerializer",
    "ClientSearchResponseSerializer",
    "ClientSearchResultSerializer",
    "ClientSerializer",
    "ClientUpdateRequestSerializer",
    "ClientUpdateResponseSerializer",
    "JobContactResponseSerializer",
    "JobContactUpdateRequestSerializer",
    "StandardErrorSerializer",
    "Supplier",
]
