# Generated by Django 6.0.1 on 2026-03-07 00:35

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0070_delete_safetydocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("procedure", "Procedure"),
                            ("form", "Form"),
                            ("register", "Register"),
                            ("reference", "Reference"),
                        ],
                        help_text="Document type: procedure, form, register, or reference",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-text tags, e.g. ["safety", "machinery", "sop"]',
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a template that can be filled in to create records",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Document lifecycle status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number for SWPs (e.g., '307' for section 3, doc 7)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job name for JSA, procedure name for SWP/SOP",
                        max_length=255,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "site_location",
                    models.CharField(
                        blank=True,
                        help_text="Work site location (optional for SWPs)",
                        max_length=500,
                    ),
                ),
                (
                    "google_doc_id",
                    models.CharField(
                        blank=True, help_text="Google Docs document ID", max_length=100
                    ),
                ),
                (
                    "google_doc_url",
                    models.URLField(
                        blank=True, help_text="URL to edit the document in Google Docs"
                    ),
                ),
                (
                    "form_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining entry fields for form templates",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked job (required for JSA, null for SWP/SOP)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_documents",
                        to="job.job",
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this record was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_records",
                        to="process.processdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Document",
                "verbose_name_plural": "Process Documents",
                "db_table": "process_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProcessDocumentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "entry_date",
                    models.DateField(help_text="Date this entry relates to"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Entry data - schema varies by document type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag - inactive entries are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Staff member who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Parent process document",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="process.processdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Process Document Entry",
                "verbose_name_plural": "historical Process Document Entries",
                "db_table": "process_historicalentry",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProcessDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("procedure", "Procedure"),
                            ("form", "Form"),
                            ("register", "Register"),
                            ("reference", "Reference"),
                        ],
                        help_text="Document type: procedure, form, register, or reference",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-text tags, e.g. ["safety", "machinery", "sop"]',
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a template that can be filled in to create records",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Document lifecycle status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number for SWPs (e.g., '307' for section 3, doc 7)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job name for JSA, procedure name for SWP/SOP",
                        max_length=255,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "site_location",
                    models.CharField(
                        blank=True,
                        help_text="Work site location (optional for SWPs)",
                        max_length=500,
                    ),
                ),
                (
                    "google_doc_id",
                    models.CharField(
                        blank=True, help_text="Google Docs document ID", max_length=100
                    ),
                ),
                (
                    "google_doc_url",
                    models.URLField(
                        blank=True, help_text="URL to edit the document in Google Docs"
                    ),
                ),
                (
                    "form_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining entry fields for form templates",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked job (required for JSA, null for SWP/SOP)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="job.job",
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Template this record was created from",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="process.processdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Process Document",
                "verbose_name_plural": "historical Process Documents",
                "db_table": "process_historicaldocument",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProcessDocumentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(help_text="Date this entry relates to"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Entry data - schema varies by document type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag - inactive entries are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Parent process document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="process.processdocument",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Document Entry",
                "verbose_name_plural": "Process Document Entries",
                "db_table": "process_entry",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
    ]
