# Generated by Django 6.0.1 on 2026-03-07 02:05

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0070_delete_safetydocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("form", "Form"), ("register", "Register")],
                        help_text="Document type: form or register",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-text tags, e.g. ["safety", "inspection"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "form_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining entry fields for form templates",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "db_table": "process_form",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(help_text="Date this entry relates to"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Entry data - schema varies by document type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag - inactive entries are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="Form definition this entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="process.form",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked job (e.g. incident forms)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_entries",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Entry",
                "verbose_name_plural": "Form Entries",
                "db_table": "process_form_entry",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalForm",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("form", "Form"), ("register", "Register")],
                        help_text="Document type: form or register",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-text tags, e.g. ["safety", "inspection"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "form_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining entry fields for form templates",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Form",
                "verbose_name_plural": "historical Forms",
                "db_table": "process_historicalform",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFormEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "entry_date",
                    models.DateField(help_text="Date this entry relates to"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Entry data - schema varies by document type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag - inactive entries are hidden from normal queries",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Staff member who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Form definition this entry belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="process.form",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked job (e.g. incident forms)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Form Entry",
                "verbose_name_plural": "historical Form Entries",
                "db_table": "process_historicalformentry",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("procedure", "Procedure"),
                            ("reference", "Reference"),
                        ],
                        help_text="Document type: procedure or reference",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number (e.g. '307' for section 3, doc 7)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "site_location",
                    models.CharField(
                        blank=True, help_text="Work site location", max_length=500
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-text tags, e.g. ["safety", "machinery", "sop"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "google_doc_id",
                    models.CharField(
                        blank=True, help_text="Google Docs document ID", max_length=100
                    ),
                ),
                (
                    "google_doc_url",
                    models.URLField(
                        blank=True, help_text="URL to edit the document in Google Docs"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked job (required for JSA, null for SWP/SOP)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Procedure",
                "verbose_name_plural": "historical Procedures",
                "db_table": "process_historicalprocedure",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("procedure", "Procedure"),
                            ("reference", "Reference"),
                        ],
                        help_text="Document type: procedure or reference",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number (e.g. '307' for section 3, doc 7)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "site_location",
                    models.CharField(
                        blank=True, help_text="Work site location", max_length=500
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-text tags, e.g. ["safety", "machinery", "sop"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "google_doc_id",
                    models.CharField(
                        blank=True, help_text="Google Docs document ID", max_length=100
                    ),
                ),
                (
                    "google_doc_url",
                    models.URLField(
                        blank=True, help_text="URL to edit the document in Google Docs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked job (required for JSA, null for SWP/SOP)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedures",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure",
                "verbose_name_plural": "Procedures",
                "db_table": "process_procedure",
                "ordering": ["-created_at"],
            },
        ),
    ]
