# Generated by Django 6.0.1 on 2026-03-07 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formentry",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member this entry is about (e.g. inductee, trainee)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalformentry",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Staff member this entry is about (e.g. inductee, trainee)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formentry",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who created this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_entries_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
