# This file is autogenerated by update_init.py script

from .archive_completed_jobs_view import (
    ArchiveCompleteJobsViews,
    StandardResultsSetPagination,
)
from .assign_job_view import JobAssignmentCreateView, JobAssignmentDeleteView
from .data_integrity_views import DataIntegrityReportView
from .data_quality_report_views import ArchivedJobsComplianceView
from .delivery_docket_view import DeliveryDocketView
from .job_costing_views import JobCostSetView, JobQuoteRevisionView
from .job_costline_views import (
    CostLineApprovalView,
    CostLineCreateView,
    CostLineDeleteView,
    CostLineUpdateView,
)
from .job_file_detail_view import BinaryFileRenderer, JobFileDetailView
from .job_file_thumbnail_view import JobFileThumbnailView
from .job_files_collection_view import JobFilesCollectionView
from .job_profitability_report_views import JobProfitabilityReportView
from .job_quote_chat_views import (
    BaseJobQuoteChatView,
    JobQuoteChatHistoryView,
    JobQuoteChatMessageView,
)
from .job_rest_views import (
    BaseJobRestView,
    JobBasicInformationRestView,
    JobCostSummaryRestView,
    JobCreateRestView,
    JobDeltaRejectionAdminRestView,
    JobDeltaRejectionListRestView,
    JobDetailRestView,
    JobEventListRestView,
    JobEventRestView,
    JobHeaderRestView,
    JobInvoicesRestView,
    JobQuoteAcceptRestView,
    JobQuoteRestView,
    JobStatusChoicesRestView,
    JobSummaryRestView,
    JobTimelineRestView,
    JobUndoChangeRestView,
    WeeklyMetricsRestView,
    get_company_defaults_api,
)
from .modern_timesheet_views import (
    ModernTimesheetDayView,
    ModernTimesheetEntryView,
    ModernTimesheetJobView,
)
from .month_end_rest_view import MonthEndRestView
from .quote_import_views import (
    QuoteImportPreviewView,
    QuoteImportStatusView,
    QuoteImportView,
)
from .quote_sync_views import (
    ApplyQuoteAPIView,
    LinkQuoteSheetAPIView,
    PreviewQuoteAPIView,
)
from .workshop_pdf_view import WorkshopPDFView
from .workshop_view import WorkshopKanbanView, WorkshopTimesheetView

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .job_quote_chat_api import JobQuoteChatInteractionView
        from .kanban_view_api import (
            AdvancedSearchAPIView,
            FetchAllJobsAPIView,
            FetchJobsAPIView,
            FetchJobsByColumnAPIView,
            FetchStatusValuesAPIView,
            ReorderJobAPIView,
            UpdateJobStatusAPIView,
        )
        from .safety_viewsets import (
            AIGenerateControlsView,
            AIGenerateHazardsView,
            AIImproveDocumentView,
            AIImproveSectionView,
            GenerateControlsRequestSerializer,
            GenerateControlsResponseSerializer,
            GenerateHazardsRequestSerializer,
            GenerateHazardsResponseSerializer,
            ImproveDocumentRequestSerializer,
            ImproveDocumentResponseSerializer,
            ImproveSectionRequestSerializer,
            ImproveSectionResponseSerializer,
            JSAGenerateView,
            JSAListView,
            SOPGenerateRequestSerializer,
            SOPGenerateView,
            SOPListView,
            SWPGenerateView,
            SWPListView,
            SafetyDocumentContentResponseSerializer,
            SafetyDocumentContentUpdateSerializer,
            SafetyDocumentContentView,
            SafetyDocumentViewSet,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AIGenerateControlsView",
    "AIGenerateHazardsView",
    "AIImproveDocumentView",
    "AIImproveSectionView",
    "AdvancedSearchAPIView",
    "ApplyQuoteAPIView",
    "ArchiveCompleteJobsViews",
    "ArchivedJobsComplianceView",
    "BaseJobQuoteChatView",
    "BaseJobRestView",
    "BinaryFileRenderer",
    "CostLineApprovalView",
    "CostLineCreateView",
    "CostLineDeleteView",
    "CostLineUpdateView",
    "DataIntegrityReportView",
    "DeliveryDocketView",
    "FetchAllJobsAPIView",
    "FetchJobsAPIView",
    "FetchJobsByColumnAPIView",
    "FetchStatusValuesAPIView",
    "GenerateControlsRequestSerializer",
    "GenerateControlsResponseSerializer",
    "GenerateHazardsRequestSerializer",
    "GenerateHazardsResponseSerializer",
    "ImproveDocumentRequestSerializer",
    "ImproveDocumentResponseSerializer",
    "ImproveSectionRequestSerializer",
    "ImproveSectionResponseSerializer",
    "JSAGenerateView",
    "JSAListView",
    "JobAssignmentCreateView",
    "JobAssignmentDeleteView",
    "JobBasicInformationRestView",
    "JobCostSetView",
    "JobCostSummaryRestView",
    "JobCreateRestView",
    "JobDeltaRejectionAdminRestView",
    "JobDeltaRejectionListRestView",
    "JobDetailRestView",
    "JobEventListRestView",
    "JobEventRestView",
    "JobFileDetailView",
    "JobFileThumbnailView",
    "JobFilesCollectionView",
    "JobHeaderRestView",
    "JobInvoicesRestView",
    "JobProfitabilityReportView",
    "JobQuoteAcceptRestView",
    "JobQuoteChatHistoryView",
    "JobQuoteChatInteractionView",
    "JobQuoteChatMessageView",
    "JobQuoteRestView",
    "JobQuoteRevisionView",
    "JobStatusChoicesRestView",
    "JobSummaryRestView",
    "JobTimelineRestView",
    "JobUndoChangeRestView",
    "LinkQuoteSheetAPIView",
    "ModernTimesheetDayView",
    "ModernTimesheetEntryView",
    "ModernTimesheetJobView",
    "MonthEndRestView",
    "PreviewQuoteAPIView",
    "QuoteImportPreviewView",
    "QuoteImportStatusView",
    "QuoteImportView",
    "ReorderJobAPIView",
    "SOPGenerateRequestSerializer",
    "SOPGenerateView",
    "SOPListView",
    "SWPGenerateView",
    "SWPListView",
    "SafetyDocumentContentResponseSerializer",
    "SafetyDocumentContentUpdateSerializer",
    "SafetyDocumentContentView",
    "SafetyDocumentViewSet",
    "StandardResultsSetPagination",
    "UpdateJobStatusAPIView",
    "WeeklyMetricsRestView",
    "WorkshopKanbanView",
    "WorkshopPDFView",
    "WorkshopTimesheetView",
    "get_company_defaults_api",
]
