# This file is autogenerated by update_init.py script

from .archive_completed_jobs_view import (
    ArchiveCompleteJobsViews,
    StandardResultsSetPagination,
)
from .assign_job_view import AssignJobView
from .job_costing_views import JobCostSetView, JobQuoteRevisionView
from .job_costline_views import (
    CostLineCreateView,
    CostLineDeleteView,
    CostLineUpdateView,
)
from .job_file_view import BinaryFileRenderer, JobFileThumbnailView, JobFileView
from .job_quote_chat_views import (
    BaseJobQuoteChatView,
    JobQuoteChatHistoryView,
    JobQuoteChatMessageView,
)
from .job_rest_views import (
    BaseJobRestView,
    JobBasicInformationRestView,
    JobCostSummaryRestView,
    JobCreateRestView,
    JobDetailRestView,
    JobEventListRestView,
    JobEventRestView,
    JobHeaderRestView,
    JobInvoicesRestView,
    JobQuoteAcceptRestView,
    JobQuoteRestView,
    JobStatusChoicesRestView,
    WeeklyMetricsRestView,
    get_company_defaults_api,
)
from .modern_timesheet_views import (
    ModernTimesheetDayView,
    ModernTimesheetEntryView,
    ModernTimesheetJobView,
)
from .month_end_rest_view import MonthEndRestView
from .quote_import_views import (
    QuoteImportPreviewView,
    QuoteImportStatusView,
    QuoteImportView,
)
from .quote_sync_views import (
    ApplyQuoteAPIView,
    LinkQuoteSheetAPIView,
    PreviewQuoteAPIView,
)
from .workshop_view import WorkshopPDFView

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .job_file_upload import JobFileUploadView
        from .job_quote_chat_api import JobQuoteChatInteractionView
        from .kanban_view_api import (
            AdvancedSearchAPIView,
            FetchAllJobsAPIView,
            FetchJobsAPIView,
            FetchJobsByColumnAPIView,
            FetchStatusValuesAPIView,
            ReorderJobAPIView,
            UpdateJobStatusAPIView,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AdvancedSearchAPIView",
    "ApplyQuoteAPIView",
    "ArchiveCompleteJobsViews",
    "AssignJobView",
    "BaseJobQuoteChatView",
    "BaseJobRestView",
    "BinaryFileRenderer",
    "CostLineCreateView",
    "CostLineDeleteView",
    "CostLineUpdateView",
    "FetchAllJobsAPIView",
    "FetchJobsAPIView",
    "FetchJobsByColumnAPIView",
    "FetchStatusValuesAPIView",
    "JobBasicInformationRestView",
    "JobCostSetView",
    "JobCostSummaryRestView",
    "JobCreateRestView",
    "JobDetailRestView",
    "JobEventListRestView",
    "JobEventRestView",
    "JobFileThumbnailView",
    "JobFileUploadView",
    "JobFileView",
    "JobHeaderRestView",
    "JobInvoicesRestView",
    "JobQuoteAcceptRestView",
    "JobQuoteChatHistoryView",
    "JobQuoteChatInteractionView",
    "JobQuoteChatMessageView",
    "JobQuoteRestView",
    "JobQuoteRevisionView",
    "JobStatusChoicesRestView",
    "LinkQuoteSheetAPIView",
    "ModernTimesheetDayView",
    "ModernTimesheetEntryView",
    "ModernTimesheetJobView",
    "MonthEndRestView",
    "PreviewQuoteAPIView",
    "QuoteImportPreviewView",
    "QuoteImportStatusView",
    "QuoteImportView",
    "ReorderJobAPIView",
    "StandardResultsSetPagination",
    "UpdateJobStatusAPIView",
    "WeeklyMetricsRestView",
    "WorkshopPDFView",
    "get_company_defaults_api",
]
