# This file is autogenerated by update_init.py script

from .client_rest_views import (
    ClientContactCreateRestView,
    ClientContactsRestView,
    ClientCreateRestView,
    ClientListAllRestView,
    ClientSearchRestView,
)

__all__ = [
    "ClientListAllRestView",
    "ClientSearchRestView",
    "ClientContactsRestView",
    "ClientContactCreateRestView",
    "ClientCreateRestView",
]
