# This file is autogenerated by update_init.py script

from .client_rest_views import (
    ClientContactCreateRestView,
    ClientContactsRestView,
    ClientCreateRestView,
    ClientJobsRestView,
    ClientListAllRestView,
    ClientRetrieveRestView,
    ClientSearchRestView,
    ClientUpdateRestView,
    JobContactRestView,
)

__all__ = [
    "ClientContactCreateRestView",
    "ClientContactsRestView",
    "ClientCreateRestView",
    "ClientJobsRestView",
    "ClientListAllRestView",
    "ClientRetrieveRestView",
    "ClientSearchRestView",
    "ClientUpdateRestView",
    "JobContactRestView",
]
