# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps
    if apps.ready:
        from .client_rest_views import (
            ClientListAllRestView,
            ClientSearchRestView,
            ClientContactsRestView,
            ClientContactCreateRestView,
            ClientCreateRestView,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "ClientContactCreateRestView",
    "ClientContactsRestView",
    "ClientCreateRestView",
    "ClientListAllRestView",
    "ClientSearchRestView",
]
