# Generated by Django 5.2 on 2025-08-09 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_initial"),
        ("job", "0040_historicaljob_fully_invoiced_job_fully_invoiced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="job.job",
            ),
        ),
    ]
