# Generated by Django 5.2 on 2025-11-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_alter_invoice_job"),
        ("client", "0009_clientcontact_unique_client_contact_name"),
        ("job", "0052_alter_costline_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="client.client"
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="client.client"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="client.client"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="job.job",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="client.client"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote",
                to="job.job",
            ),
        ),
    ]
