# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps
    if apps.ready:
        from .password_views import SecurityPasswordChangeView
        from .staff_api import StaffListCreateAPIView, StaffRetrieveUpdateDestroyAPIView
        from .staff_views import (
            StaffListAPIView,
            StaffListView,
            StaffCreateView,
            StaffUpdateView,
            get_staff_rates,
        )
        from .token_view import CustomTokenObtainPairView, CustomTokenRefreshView
        from .user_profile_view import GetCurrentUserAPIView, LogoutUserAPIView
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CustomTokenObtainPairView",
    "CustomTokenRefreshView",
    "GetCurrentUserAPIView",
    "LogoutUserAPIView",
    "SecurityPasswordChangeView",
    "StaffCreateView",
    "StaffListAPIView",
    "StaffListCreateAPIView",
    "StaffListView",
    "StaffRetrieveUpdateDestroyAPIView",
    "StaffUpdateView",
    "get_staff_rates",
]
