# This file is autogenerated by update_init.py script

from .bearer_token_view import BearerTokenView
from .password_views import SecurityPasswordChangeView
from .token_view import CustomTokenObtainPairView, CustomTokenRefreshView, get_client_ip
from .user_profile_view import GetCurrentUserAPIView, LogoutUserAPIView

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .staff_api import StaffListCreateAPIView, StaffRetrieveUpdateDestroyAPIView
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

# EXCLUDED IMPORTS - These contain problematic dependencies that cause circular imports
# Import these directly where needed using:
# from .staff_views import StaffCreateView
# from .staff_views import StaffListAPIView
# from .staff_views import StaffListView
# from .staff_views import StaffUpdateView
# from .staff_views import get_staff_rates
#

__all__ = [
    "BearerTokenView",
    "CustomTokenObtainPairView",
    "CustomTokenRefreshView",
    "GetCurrentUserAPIView",
    "LogoutUserAPIView",
    "SecurityPasswordChangeView",
    "StaffListCreateAPIView",
    "StaffRetrieveUpdateDestroyAPIView",
    "get_client_ip",
]
