# Generated by Django 5.2 on 2025-07-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0166_alter_apperror_options_alter_xeroerror_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aiprovider',
            table='workflow_aiprovider',
        ),
    ]
