# Generated by Django 5.2 on 2025-09-07 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0168_enhance_app_error_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiprovider",
            name="company",
        ),
    ]
