# Generated by Django 5.2 on 2025-11-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0169_remove_aiprovider_company_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="test_client_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the test client used for testing (e.g., 'ABC Carpet Cleaning TEST IGNORE'). This client's name is preserved during data backports.",
                max_length=255,
                null=True,
            ),
        ),
    ]
