# Generated by Django 5.2 on 2025-11-03 02:32

from django.db import migrations, models


def update_existing_token_scopes(apps, schema_editor):
    """Add payroll scopes to existing XeroToken records."""
    XeroToken = apps.get_model("workflow", "XeroToken")

    new_scopes = "payroll.timesheets payroll.employees payroll.settings"

    for token in XeroToken.objects.all():
        # Only add if not already present
        if "payroll" not in token.scope:
            token.scope = f"{token.scope} {new_scopes}"
            token.save(update_fields=["scope"])


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0169_remove_aiprovider_company_field"),
    ]

    operations = [
        # Leave Type IDs (use Xero Leave API, not earnings rates)
        migrations.AddField(
            model_name="companydefaults",
            name="xero_annual_leave_type_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll Leave Type ID for Annual Leave",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="xero_sick_leave_type_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll Leave Type ID for Sick Leave",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="xero_other_leave_type_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll Leave Type ID for Other Leave",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="xero_unpaid_leave_type_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll Leave Type ID for Unpaid Leave",
                max_length=100,
                null=True,
            ),
        ),
        # Work Time Earnings Rate IDs (use Xero Timesheets API)
        migrations.AddField(
            model_name="companydefaults",
            name="xero_ordinary_earnings_rate_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll earnings rate ID for Ordinary Time (1.0x)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="xero_time_half_earnings_rate_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll earnings rate ID for Time and a Half (1.5x)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="xero_double_time_earnings_rate_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Payroll earnings rate ID for Double Time (2.0x)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.transactions accounting.reports.read accounting.settings accounting.journals.read payroll.timesheets payroll.employees payroll.settings"
            ),
        ),
        migrations.RunPython(
            update_existing_token_scopes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
