# Generated by Django 5.2 on 2025-11-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0171_protect_critical_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.transactions accounting.reports.read accounting.settings accounting.journals.read projects payroll.timesheets payroll.payruns payroll.employees payroll.settings"
            ),
        ),
    ]
