# Generated by Django 5.2 on 2025-12-11 00:46

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0173_add_test_client_name_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroPayRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payroll_calendar_id", models.UUIDField(blank=True, null=True)),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "pay_run_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pay_run_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Run",
                "verbose_name_plural": "Xero Pay Runs",
                "db_table": "workflow_xeropayrun",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="XeroPaySlip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("xero_employee_id", models.UUIDField()),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "timesheet_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from timesheet_earnings_lines (actual worked hours)",
                        max_digits=8,
                    ),
                ),
                (
                    "leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Hours from leave_earnings_lines (sick, annual, etc.)",
                        max_digits=8,
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_slips",
                        to="workflow.xeropayrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xero Pay Slip",
                "verbose_name_plural": "Xero Pay Slips",
                "db_table": "workflow_xeropayslip",
                "ordering": ["-pay_run__payment_date", "employee_name"],
                "unique_together": {("pay_run", "xero_employee_id")},
            },
        ),
    ]
