# Generated by Django 5.2 on 2025-12-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0174_add_xero_payroll_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xeropayrun",
            name="xero_last_modified",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="xeropayrun",
            name="xero_tenant_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="xeropayslip",
            name="xero_last_modified",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="xeropayslip",
            name="xero_tenant_id",
            field=models.CharField(max_length=255),
        ),
    ]
