# Generated by Django 5.2 on 2025-12-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0175_make_payroll_fields_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="address_line1",
            field=models.CharField(
                blank=True, help_text="Street address line 1", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="address_line2",
            field=models.CharField(
                blank=True,
                help_text="Street address line 2 (optional)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="city",
            field=models.CharField(
                blank=True, help_text="City", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="country",
            field=models.CharField(
                default="New Zealand", help_text="Country name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="post_code",
            field=models.CharField(
                blank=True, help_text="Postal/ZIP code", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="suburb",
            field=models.CharField(
                blank=True,
                help_text="Suburb (for NZ addresses)",
                max_length=100,
                null=True,
            ),
        ),
    ]
