# Generated by Django 5.2 on 2025-12-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0176_add_company_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="company_email",
            field=models.EmailField(
                blank=True,
                help_text="Company contact email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="company_url",
            field=models.URLField(
                blank=True, help_text="Company website URL", null=True
            ),
        ),
    ]
