# Generated by Django 5.2 on 2025-12-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0177_add_company_email_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="company_acronym",
            field=models.CharField(
                blank=True,
                help_text="Short acronym for the company (e.g., 'MSM' for Morris Sheetmetal)",
                max_length=10,
                null=True,
            ),
        ),
    ]
