# Generated by Django 5.2 on 2025-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0178_add_company_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="xero_payroll_calendar_name",
            field=models.CharField(
                default="Weekly",
                help_text="Name of Xero Payroll calendar to use (e.g., 'Weekly 2025')",
                max_length=100,
            ),
        ),
    ]
