# Generated by Django 5.2 on 2025-12-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0179_add_xero_payroll_calendar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.transactions accounting.reports.read accounting.settings accounting.journals.read projects payroll.timesheets payroll.payruns payroll.payslip payroll.employees payroll.settings"
            ),
        ),
    ]
