# Generated by Django 5.2 on 2025-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0180_alter_xerotoken_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal identifier (e.g., 'annual_leave', 'work_ordinary')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Annual Leave', 'Ordinary Time')",
                        max_length=100,
                    ),
                ),
                (
                    "job_name_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Substring to match in job name (e.g., 'annual leave'). Case-insensitive. Leave blank for work rate categories.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rate_multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Rate multiplier for work entries (e.g., 1.0, 1.5, 2.0). Leave blank for leave type categories.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "posts_to_xero",
                    models.BooleanField(
                        default=True,
                        help_text="Whether entries in this category are posted to Xero payroll",
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        default=False,
                        help_text="True = use Xero Leave API (for leave with balances). False = use Xero Timesheets API.",
                    ),
                ),
                (
                    "xero_leave_type_name",
                    models.CharField(
                        blank=True,
                        help_text="Xero Leave Type name (looked up at runtime to get ID). Required if uses_leave_api=True.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "xero_earnings_rate_name",
                    models.CharField(
                        blank=True,
                        help_text="Xero Earnings Rate name (looked up at runtime to get ID). Required if uses_leave_api=False and posts_to_xero=True.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Category",
                "verbose_name_plural": "Payroll Categories",
                "ordering": ["name"],
            },
        ),
    ]
