# Generated by Django 5.2 on 2025-12-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0182_populate_payroll_categories"),
    ]

    operations = [
        # Use RunSQL with IF EXISTS because schema may predate migration 0170
        # which added these columns. They may not exist in restored backups.
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_annual_leave_type_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_double_time_earnings_rate_name;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_ordinary_earnings_rate_name;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_other_leave_type_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_sick_leave_type_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_time_half_earnings_rate_name;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE workflow_companydefaults DROP COLUMN IF EXISTS xero_unpaid_leave_type_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
