# Generated by Django 5.2 on 2025-12-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0182_populate_payroll_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_annual_leave_type_id",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_double_time_earnings_rate_name",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_ordinary_earnings_rate_name",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_other_leave_type_id",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_sick_leave_type_id",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_time_half_earnings_rate_name",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="xero_unpaid_leave_type_id",
        ),
    ]
