# Generated by Django 5.2 on 2025-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0183_remove_payroll_fields_from_companydefaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="xero_shortcode",
            field=models.CharField(
                blank=True,
                help_text="Xero organisation shortcode for deep linking (e.g., '!8-5Xl')",
                max_length=20,
                null=True,
            ),
        ),
    ]
