# Generated by Django 5.2 on 2025-12-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0183_remove_payroll_fields_from_companydefaults"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payrollcategory",
            old_name="xero_leave_type_id",
            new_name="xero_leave_type_name",
        ),
    ]
