# Generated by Django 5.2 on 2025-12-30 23:32

from django.db import migrations, models


def fix_payroll_categories(apps, schema_editor):
    """
    Fix payroll category configuration:

    1. unpaid_leave: was incorrectly configured with posts_to_xero=False and
       uses_leave_api=False. Now uses Leave API like annual/sick leave.

    2. other_leave: renamed to bereavement_leave and configured to use Leave API
       with proper Xero leave type mapping.
    """
    PayrollCategory = apps.get_model("workflow", "PayrollCategory")

    # Fix unpaid_leave
    PayrollCategory.objects.filter(name="unpaid_leave").update(uses_leave_api=True)

    # Rename other_leave to bereavement_leave and configure properly
    PayrollCategory.objects.filter(name="other_leave").update(
        name="bereavement_leave",
        display_name="Bereavement Leave",
        job_name_pattern="bereavement leave",
        uses_leave_api=True,
        xero_leave_type_name="Bereavement Leave",
    )


def reverse_fix(apps, schema_editor):
    """Reverse the payroll category fixes."""
    PayrollCategory = apps.get_model("workflow", "PayrollCategory")

    # Revert unpaid_leave
    PayrollCategory.objects.filter(name="unpaid_leave").update(uses_leave_api=False)

    # Revert bereavement_leave back to other_leave
    PayrollCategory.objects.filter(name="bereavement_leave").update(
        name="other_leave",
        display_name="Other Leave",
        job_name_pattern="other leave",
        uses_leave_api=False,
        xero_leave_type_name=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0184_add_xero_shortcode"),
    ]

    operations = [
        # Fix unpaid_leave and rename other_leave to bereavement_leave
        migrations.RunPython(fix_payroll_categories, reverse_fix),
        # Then remove the redundant posts_to_xero field
        migrations.RemoveField(
            model_name="payrollcategory",
            name="posts_to_xero",
        ),
        migrations.AlterField(
            model_name="payrollcategory",
            name="xero_earnings_rate_name",
            field=models.CharField(
                blank=True,
                help_text="Xero Earnings Rate name (looked up at runtime to get ID). Required if uses_leave_api=False (work entries).",
                max_length=100,
                null=True,
            ),
        ),
    ]
