# Generated by Django 5.2 on 2025-12-31 04:18

import uuid
from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


def create_seed_xero_pay_items(apps, schema_editor):
    """Create seed XeroPayItem records needed by migration 0064."""
    XeroPayItem = apps.get_model("workflow", "XeroPayItem")

    seed_items = [
        # Earnings rates (uses_leave_api=False)
        {
            "name": "Ordinary Time",
            "uses_leave_api": False,
            "multiplier": Decimal("1.0"),
            "xero_id": "seed-ordinary-time",
            "xero_tenant_id": "pending-sync",
        },
        {
            "name": "Time and one half",
            "uses_leave_api": False,
            "multiplier": Decimal("1.5"),
            "xero_id": "seed-time-half",
            "xero_tenant_id": "pending-sync",
        },
        {
            "name": "Double Time",
            "uses_leave_api": False,
            "multiplier": Decimal("2.0"),
            "xero_id": "seed-double-time",
            "xero_tenant_id": "pending-sync",
        },
        # Leave types (uses_leave_api=True)
        {
            "name": "Annual Leave",
            "uses_leave_api": True,
            "multiplier": None,
            "xero_id": "seed-annual-leave",
            "xero_tenant_id": "pending-sync",
        },
        {
            "name": "Sick Leave",
            "uses_leave_api": True,
            "multiplier": None,
            "xero_id": "seed-sick-leave",
            "xero_tenant_id": "pending-sync",
        },
        {
            "name": "Unpaid Leave",
            "uses_leave_api": True,
            "multiplier": None,
            "xero_id": "seed-unpaid-leave",
            "xero_tenant_id": "pending-sync",
        },
        {
            "name": "Bereavement Leave",
            "uses_leave_api": True,
            "multiplier": None,
            "xero_id": "seed-bereavement-leave",
            "xero_tenant_id": "pending-sync",
        },
    ]

    for item in seed_items:
        XeroPayItem.objects.create(**item)
    print(f"  Created {len(seed_items)} seed XeroPayItem records")


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0186_simplify_payroll_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroPayItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        help_text="Xero's UUID for this pay item",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        help_text="Xero tenant this pay item belongs to", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ordinary Time', 'Annual Leave')",
                        max_length=100,
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        help_text="True = Xero Leave API, False = Xero Timesheets API"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate multiplier from Xero (1.0, 1.5, 2.0, etc.). NULL for leave types.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified timestamp from Xero",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="When we last synced this record from Xero",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Item",
                "verbose_name_plural": "Xero Pay Items",
                "db_table": "workflow_xeropayitem",
                "ordering": ["uses_leave_api", "name"],
            },
        ),
        migrations.RunPython(create_seed_xero_pay_items, migrations.RunPython.noop),
    ]
