# Generated by Django 5.2 on 2025-12-31 04:18

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0186_simplify_payroll_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroPayItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_id",
                    models.CharField(
                        help_text="Xero's UUID for this pay item",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(
                        help_text="Xero tenant this pay item belongs to", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ordinary Time', 'Annual Leave')",
                        max_length=100,
                    ),
                ),
                (
                    "uses_leave_api",
                    models.BooleanField(
                        help_text="True = Xero Leave API, False = Xero Timesheets API"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate multiplier from Xero (1.0, 1.5, 2.0, etc.). NULL for leave types.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "xero_last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified timestamp from Xero",
                        null=True,
                    ),
                ),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="When we last synced this record from Xero",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Xero Pay Item",
                "verbose_name_plural": "Xero Pay Items",
                "db_table": "workflow_xeropayitem",
                "ordering": ["uses_leave_api", "name"],
            },
        ),
    ]
