# Generated by Django 5.2 on 2026-01-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0188_delete_payrollcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="xero_payroll_calendar_id",
            field=models.UUIDField(
                blank=True,
                help_text="Cached Xero Payroll calendar ID (set by setup_xero command)",
                null=True,
            ),
        ),
    ]
