# Generated by Django 5.2 on 2026-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0189_add_xero_payroll_calendar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("Claude", "Anthropic"),
                    ("Gemini", "Google"),
                    ("Mistral", "Mistral"),
                    ("OpenAI", "Openai"),
                ],
                help_text="Type of AI provider",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="xero_payroll_calendar_id",
            field=models.UUIDField(
                blank=True,
                help_text="Cached Xero Payroll calendar ID (set by xero --setup command)",
                null=True,
            ),
        ),
    ]
