# Generated by Django 6.0.1 on 2026-02-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0193_add_job_gp_target_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="profit_threshold_amber",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Monthly net profit between this threshold and the green threshold is marked in amber",
                max_digits=10,
                verbose_name="Amber Threshold of Monthly Net Profit",
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="profit_threshold_green",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text="Monthly net profit above this threshold is marked in green",
                max_digits=10,
                verbose_name="Green Threshold of Monthly Net Profit",
            ),
        ),
    ]
