# Generated by Django 6.0.1 on 2026-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0195_rename_kpi_threshold_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_billable_hours_amber",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily total billable hours across all staff above which the day is amber",
                max_digits=5,
                verbose_name="Daily billable hours (amber)",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_billable_hours_green",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily total billable hours across all staff above which the day is green",
                max_digits=5,
                verbose_name="Daily billable hours (green)",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_gp_target",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily gross profit target in dollars",
                max_digits=10,
                verbose_name="Daily gross profit target",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_gp_amber",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily gross profit above which the day is amber",
                max_digits=10,
                verbose_name="Daily GP (amber)",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_gp_green",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily gross profit above which the day is green",
                max_digits=10,
                verbose_name="Daily GP (green)",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_daily_shop_hours_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Target percentage of daily hours spent on shop (non-billable) jobs",
                max_digits=5,
                verbose_name="Daily shop hours percentage target",
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="kpi_job_gp_target_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Target gross profit percentage for individual jobs",
                max_digits=5,
                verbose_name="Target GP % per job",
            ),
        ),
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.transactions accounting.attachments accounting.reports.read accounting.settings accounting.journals.read projects payroll.timesheets payroll.payruns payroll.payslip payroll.employees payroll.settings"
            ),
        ),
    ]
