# Generated by Django 6.0.1 on 2026-02-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow",
            "0196_alter_companydefaults_kpi_daily_billable_hours_amber_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.transactions accounting.attachments accounting.reports.read accounting.settings accounting.journals.read projects payroll.timesheets payroll.payruns payroll.payslip payroll.employees payroll.settings"
            ),
        ),
    ]
