# Generated by Django 6.0.1 on 2026-03-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0197_alter_xerotoken_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="gdrive_how_we_work_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Folder ID for '01 - How we work' (policies, basics)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="gdrive_reference_library_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Folder ID for '03 - Reference Library' (reference documents, forms, registers)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="gdrive_sops_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Folder ID for '02 - SOPs' (standard operating procedures)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="google_shared_drive_id",
            field=models.CharField(
                blank=True,
                help_text="Google Shared Drive ID for the company shared drive",
                max_length=100,
                null=True,
            ),
        ),
    ]
