# Generated by Django 6.0.1 on 2026-03-03 01:32

from django.db import migrations


def populate_shared_drive_ids(apps, schema_editor):
    CompanyDefaults = apps.get_model("workflow", "CompanyDefaults")
    for company in CompanyDefaults.objects.all():
        company.google_shared_drive_id = "0AHbDQDoGRnn-Uk9PVA"
        company.gdrive_reference_library_folder_id = "1Bl9E0jLfcE45tbItT6FAzQ9L6lkxX5iJ"
        company.save(
            update_fields=[
                "google_shared_drive_id",
                "gdrive_reference_library_folder_id",
            ]
        )


def reverse_populate(apps, schema_editor):
    CompanyDefaults = apps.get_model("workflow", "CompanyDefaults")
    CompanyDefaults.objects.all().update(
        google_shared_drive_id=None,
        gdrive_reference_library_folder_id=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0198_add_shared_drive_fields"),
    ]

    operations = [
        migrations.RunPython(populate_shared_drive_ids, reverse_populate),
    ]
