# Generated by Django 5.2 on 2025-07-01 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0028_add_job_quote_chat_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="material_gauge_quantity",
        ),
        migrations.RemoveField(
            model_name="job",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="job",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="job",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="job",
            name="material_gauge_quantity",
        ),
    ]
