# Generated by Django 5.2 on 2025-07-07 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0030_migrate_pricing_to_costing_and_cleanup"),
        ("timesheet", "0003_delete_timeentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpart",
            name="job_pricing",
        ),
        migrations.RemoveField(
            model_name="jobpricing",
            name="default_part",
        ),
        migrations.RemoveField(
            model_name="jobpricing",
            name="job",
        ),
        migrations.RemoveField(
            model_name="job",
            name="latest_quote_pricing",
        ),
        migrations.RemoveField(
            model_name="materialentry",
            name="job_pricing",
        ),
        migrations.RemoveField(
            model_name="quotepricing",
            name="jobpricing_ptr",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="latest_reality_pricing",
        ),
        migrations.RemoveField(
            model_name="job",
            name="latest_estimate_pricing",
        ),
        migrations.RemoveField(
            model_name="job",
            name="latest_reality_pricing",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="latest_quote_pricing",
        ),
        migrations.RemoveField(
            model_name="job",
            name="archived_pricings",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="latest_estimate_pricing",
        ),
        migrations.RemoveField(
            model_name="materialentry",
            name="purchase_order_line",
        ),
        migrations.RemoveField(
            model_name="materialentry",
            name="source_stock",
        ),
        migrations.DeleteModel(
            name="AdjustmentEntry",
        ),
        migrations.DeleteModel(
            name="JobPart",
        ),
        migrations.DeleteModel(
            name="QuotePricing",
        ),
        migrations.DeleteModel(
            name="JobPricing",
        ),
        migrations.DeleteModel(
            name="MaterialEntry",
        ),
    ]
