# Generated by Django 5.2 on 2025-07-24 01:38
# Remove legacy status choices from Job and HistoricalJob models

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0033_update_job_statuses_for_simplified_kanban"),
    ]

    operations = [
        # Update status choices for Job model - remove legacy choices
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_approval", "Awaiting Approval"),
                    ("approved", "Approved"),
                    ("in_progress", "In Progress"),
                    ("unusual", "Unusual"),
                    ("recently_completed", "Recently Completed"),
                    ("special", "Special"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        # Update status choices for HistoricalJob model - remove legacy choices
        migrations.AlterField(
            model_name="historicaljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_approval", "Awaiting Approval"),
                    ("approved", "Approved"),
                    ("in_progress", "In Progress"),
                    ("unusual", "Unusual"),
                    ("recently_completed", "Recently Completed"),
                    ("special", "Special"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
