# Generated by Django 5.2 on 2025-08-04 21:40
# Refactored version merging 0038 and 0039 migrations
# Removes deduplication logic, keeps only schema changes

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0037_finalize_uuid_transition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add dedup_hash field
        migrations.AddField(
            model_name="jobevent",
            name="dedup_hash",
            field=models.CharField(
                blank=True,
                help_text="MD5 hash for deduplication based on job+staff+description+type",
                max_length=64,
                null=True,
            ),
        ),
        # Add optimized indexes
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["job", "-timestamp"], name="jobevent_job_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["event_type", "-timestamp"], name="jobevent_type_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["staff", "-timestamp"], name="jobevent_staff_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(fields=["dedup_hash"], name="jobevent_dedup_hash_idx"),
        ),
        # Add unique constraint (without condition for MariaDB compatibility)
        migrations.AddConstraint(
            model_name="jobevent",
            constraint=models.UniqueConstraint(
                fields=("job", "staff", "event_type", "dedup_hash"),
                name="unique_manual_event_per_user_job",
            ),
        ),
    ]
