# Generated by Django 5.2 on 2025-08-04 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0038_add_event_deduplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # I found out MariaDB does not support the condition argument in UniqueConstraint, so I had to remove it.
    # The constraing will work though.
    operations = [
        migrations.RemoveConstraint(
            model_name="jobevent",
            name="unique_manual_event_per_user_job",
        ),
        migrations.AddConstraint(
            model_name="jobevent",
            constraint=models.UniqueConstraint(
                fields=("job", "staff", "event_type", "dedup_hash"),
                name="unique_manual_event_per_user_job",
            ),
        ),
    ]
