# Generated by Django 5.2 on 2025-08-09 22:20

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0038_add_event_deduplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-priority", "-created_at"],
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.AddField(
            model_name="costline",
            name="xero_expense_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costline",
            name="xero_last_modified",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 9, 22, 20, 33, 90501, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costline",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="costline",
            name="xero_time_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="xero_last_modified",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 9, 22, 20, 39, 498380, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="xero_project_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="xero_last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="xero_project_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
