# Generated by Django 5.2 on 2025-08-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0039_alter_job_options_costline_xero_expense_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="fully_invoiced",
            field=models.BooleanField(
                default=False,
                help_text="The total value of invoices for this job matches the total value of the job.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="fully_invoiced",
            field=models.BooleanField(
                default=False,
                help_text="The total value of invoices for this job matches the total value of the job.",
            ),
        ),
    ]
