# Generated by Django 5.2 on 2025-08-09 22:37

from django.db import migrations


def populate_fully_invoiced_forward(apps, schema_editor):
    """Set fully_invoiced=True for jobs that currently have invoices."""
    Job = apps.get_model("job", "Job")
    apps.get_model("accounting", "Invoice")

    # Get all jobs that have at least one invoice
    jobs_with_invoices = Job.objects.filter(invoices__isnull=False).distinct()

    updated_count = jobs_with_invoices.update(fully_invoiced=True)
    print(
        f"Updated {updated_count} jobs to fully_invoiced=True based on existing invoices"
    )


def populate_fully_invoiced_reverse(apps, schema_editor):
    """Reset all fully_invoiced flags to False."""
    Job = apps.get_model("job", "Job")
    Job.objects.update(fully_invoiced=False)
    print("Reset all jobs to fully_invoiced=False")


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0040_historicaljob_fully_invoiced_job_fully_invoiced"),
        (
            "accounting",
            "0003_alter_invoice_job",
        ),  # Need this to ensure ForeignKey relationship exists
    ]

    operations = [
        migrations.RunPython(
            populate_fully_invoiced_forward,
            populate_fully_invoiced_reverse,
        ),
    ]
