# Generated by Django 5.2 on 2025-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0041_populate_fully_invoiced"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="xero_default_task_id",
            field=models.CharField(
                blank=True,
                help_text="Xero task ID for the default Labor task used for time entries",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="xero_default_task_id",
            field=models.CharField(
                blank=True,
                help_text="Xero task ID for the default Labor task used for time entries",
                max_length=255,
                null=True,
            ),
        ),
    ]
