# Generated by Django 5.2.5 on 2025-08-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0042_add_xero_default_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costline",
            name="xero_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="xero_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="xero_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
