# Generated by Django 5.2 on 2025-09-20 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0043_alter_costline_xero_last_modified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costline",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="costline",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="costline",
            index=models.Index(
                fields=["cost_set_id", "created_at"],
                name="job_costlin_cost_se_c0dcd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costline",
            index=models.Index(
                fields=["cost_set_id", "kind", "created_at"],
                name="job_costlin_cost_se_a4dadb_idx",
            ),
        ),
    ]
