# Generated by Django 5.2 on 2025-10-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0046_add_delta_fields_to_job_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobdeltarejection",
            new_name="job_delta_rej_change_idx",
            old_name="job_delta_rejection_change_idx",
        ),
        migrations.RenameIndex(
            model_name="jobdeltarejection",
            new_name="job_delta_rej_created_idx",
            old_name="job_delta_rejection_created_idx",
        ),
        migrations.AddField(
            model_name="costline",
            name="accounting_date",
            field=models.DateField(
                blank=True,
                help_text="The date this cost should be attributed to for accounting purposes",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobdeltarejection",
            name="change_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
