# Generated by Django 5.2 on 2025-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0048_populate_accounting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costline",
            name="accounting_date",
            field=models.DateField(
                help_text="The date this cost should be attributed to for accounting purposes"
            ),
        ),
        migrations.AlterField(
            model_name="costline",
            name="meta",
            field=models.JSONField(
                default=dict,
                help_text="Additional metadata - structure varies by kind (see class docstring)",
            ),
        ),
    ]
