# Generated by Django 5.2 on 2025-10-19 17:29

from django.db import migrations, models

import apps.job.models.costing


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0050_backfill_costset_summaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costset",
            name="summary",
            field=models.JSONField(
                default=apps.job.models.costing.get_default_cost_set_summary,
                help_text="Summary data for this cost set (cost, rev, hours)",
            ),
        ),
    ]
