# Generated by Django 5.2 on 2025-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0051_fix_costset_summary_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costline",
            name="desc",
            field=models.CharField(
                blank=True, help_text="Description of this cost line", max_length=255
            ),
        ),
    ]
