# Generated by Django 5.2 on 2025-11-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0052_alter_costline_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="speed_quality_tradeoff",
            field=models.CharField(
                choices=[
                    ("fast", "Fast - Prioritize Speed"),
                    ("normal", "Normal - Balanced"),
                    ("quality", "Quality - Prioritize Quality"),
                ],
                default="normal",
                help_text="Speed vs quality tradeoff for workshop execution",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="speed_quality_tradeoff",
            field=models.CharField(
                choices=[
                    ("fast", "Fast - Prioritize Speed"),
                    ("normal", "Normal - Balanced"),
                    ("quality", "Quality - Prioritize Quality"),
                ],
                default="normal",
                help_text="Speed vs quality tradeoff for workshop execution",
                max_length=20,
            ),
        ),
    ]
