# Generated by Django 5.2 on 2025-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0054_protect_critical_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="price_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount to invoice for T&M jobs (do not exceed). For quoted jobs it is set to the quote.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="price_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum amount to invoice for T&M jobs (do not exceed). For quoted jobs it is set to the quote.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
