# Generated by Django 5.2 on 2025-12-08 19:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0055_add_price_cap"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("jsa", "Job Safety Analysis"),
                            ("swp", "Safe Work Procedure"),
                        ],
                        help_text="Type of safety document (JSA or SWP)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")],
                        default="draft",
                        help_text="Draft = editable, Final = PDF generated",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Job name for JSA, procedure name for SWP",
                        max_length=255,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "site_location",
                    models.CharField(
                        blank=True,
                        help_text="Work site location (optional for SWPs)",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Job description for JSA, procedure scope for SWP"
                    ),
                ),
                (
                    "ppe_requirements",
                    models.JSONField(
                        default=list,
                        help_text='List of required PPE items, e.g. ["Hard hat", "Safety glasses"]',
                    ),
                ),
                (
                    "tasks",
                    models.JSONField(
                        default=list,
                        help_text="Array of task objects with hazards and controls",
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional safety notes or site-specific requirements",
                    ),
                ),
                (
                    "pdf_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Relative path from DROPBOX_WORKFLOW_FOLDER to generated PDF",
                        max_length=500,
                    ),
                ),
                (
                    "context_document_ids",
                    models.JSONField(
                        default=list,
                        help_text="UUIDs of documents used as context during generation",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked job (required for JSA, null for SWP)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_documents",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Document",
                "verbose_name_plural": "Safety Documents",
                "db_table": "workflow_safetydocument",
                "ordering": ["-created_at"],
            },
        ),
    ]
