# Generated by Django 5.2 on 2025-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0057_safetydocument_google_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetydocument",
            name="document_number",
            field=models.CharField(
                blank=True,
                help_text="Document number for SWPs (e.g., '307' for section 3, doc 7)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="safetydocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("jsa", "Job Safety Analysis"),
                    ("swp", "Safe Work Procedure"),
                    ("sop", "Standard Operating Procedure"),
                ],
                help_text="Type of safety document (JSA or SWP)",
                max_length=3,
            ),
        ),
    ]
