# Generated by Django 5.2 on 2025-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0058_safetydocument_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costline",
            name="approved",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this line is approved or not by an office staff (when the line is created by a workshop worker)",
            ),
        ),
    ]
