# Generated by Django 5.2 on 2025-12-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0059_costline_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="rejected_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this job was rejected (shown in Archived with rejected styling)",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="rejected_flag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this job was rejected (shown in Archived with rejected styling)",
            ),
        ),
    ]
