# Generated by Django 5.2 on 2026-01-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0064_job_default_xero_pay_item"),
        ("workflow", "0188_delete_payrollcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="default_xero_pay_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Default pay item for time entry. Prepopulates dropdown, can be overridden.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflow.xeropayitem",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="default_xero_pay_item",
            field=models.ForeignKey(
                help_text="Default pay item for time entry. Prepopulates dropdown, can be overridden.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="workflow.xeropayitem",
            ),
        ),
    ]
