# Generated by Django 5.2 on 2026-01-01

from django.db import migrations


def zero_shop_job_revenue(apps, _schema_editor):
    """Zero out revenue and set is_billable=False for all shop job cost lines.

    Shop jobs are internal jobs that cannot have revenue. This migration
    ensures all existing data conforms to this invariant.

    Additionally, "Unpaid Leave" entries should have zero cost (no wages paid).
    """
    CostLine = apps.get_model("job", "CostLine")
    CostSet = apps.get_model("job", "CostSet")
    Job = apps.get_model("job", "Job")
    Client = apps.get_model("client", "Client")
    CompanyDefaults = apps.get_model("workflow", "CompanyDefaults")

    # Get shop client ID - FAIL FAST if not configured
    company_defaults = CompanyDefaults.objects.first()
    if not company_defaults:
        raise RuntimeError("CompanyDefaults not configured")
    if not company_defaults.shop_client_name:
        raise RuntimeError("shop_client_name not configured in CompanyDefaults")

    shop_client = Client.objects.filter(name=company_defaults.shop_client_name).first()
    if not shop_client:
        raise RuntimeError(
            f"Shop client '{company_defaults.shop_client_name}' not found"
        )

    # Get shop job cost sets
    shop_jobs = Job.objects.filter(client_id=shop_client.id)
    shop_job_count = shop_jobs.count()
    print(f"  Found {shop_job_count} shop jobs")

    # Find Unpaid Leave job for special handling
    unpaid_leave_job = shop_jobs.filter(name="Unpaid Leave").first()
    unpaid_leave_costset_ids = []
    if unpaid_leave_job:
        unpaid_leave_costset_ids = list(
            CostSet.objects.filter(job=unpaid_leave_job).values_list("id", flat=True)
        )

    shop_costsets = CostSet.objects.filter(job__in=shop_jobs)
    shop_costset_ids = list(shop_costsets.values_list("id", flat=True))

    # Update cost lines
    updated_revenue_count = 0
    updated_billable_count = 0
    updated_cost_count = 0

    for line in CostLine.objects.filter(cost_set_id__in=shop_costset_ids):
        changed = False
        update_fields = []

        # Zero out revenue for all shop jobs
        if line.unit_rev != 0:
            line.unit_rev = 0
            updated_revenue_count += 1
            update_fields.append("unit_rev")
            changed = True

        # Zero out cost for Unpaid Leave (no wages paid)
        if line.cost_set_id in unpaid_leave_costset_ids and line.unit_cost != 0:
            line.unit_cost = 0
            updated_cost_count += 1
            update_fields.append("unit_cost")
            changed = True

        # Set is_billable=False for time entries
        if line.kind == "time":
            meta = line.meta or {}
            if meta.get("is_billable", True):
                meta["is_billable"] = False
                line.meta = meta
                updated_billable_count += 1
                update_fields.append("meta")
                changed = True

        if changed:
            line.save(update_fields=update_fields)

    print(
        f"  Updated {updated_revenue_count} cost lines with non-zero revenue, "
        f"{updated_billable_count} time entries marked as non-billable, "
        f"{updated_cost_count} Unpaid Leave entries zeroed cost"
    )


def noop(_apps, _schema_editor):
    """Reverse migration - cannot restore original revenue/cost values."""


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0065_make_default_xero_pay_item_required"),
        ("client", "0001_initial"),
        ("workflow", "0188_delete_payrollcategory"),
    ]

    operations = [
        migrations.RunPython(zero_shop_job_revenue, noop),
    ]
