# Generated by Django 6.0.1 on 2026-02-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0067_normalize_wage_rate_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically when job moves to recently_completed or archived",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically when job moves to recently_completed or archived",
                null=True,
            ),
        ),
    ]
