# Generated by Django 6.0.1 on 2026-03-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0069_fix_fully_invoiced"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SafetyDocument",
        ),
    ]
