# Generated by Django 6.0.1 on 2026-03-02 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0069_fix_fully_invoiced"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SafetyDocument",
            new_name="ProcessDocument",
        ),
        migrations.AlterModelOptions(
            name="processdocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Process Document",
                "verbose_name_plural": "Process Documents",
            },
        ),
        migrations.AlterField(
            model_name="processdocument",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked job (required for JSA, null for SWP/SOP)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="process_documents",
                to="job.job",
            ),
        ),
        migrations.AlterField(
            model_name="processdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("jsa", "Job Safety Analysis"),
                    ("swp", "Safe Work Procedure"),
                    ("sop", "Standard Operating Procedure"),
                ],
                help_text="Type of process document (JSA, SWP, or SOP)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="processdocument",
            name="title",
            field=models.CharField(
                help_text="Job name for JSA, procedure name for SWP/SOP",
                max_length=255,
            ),
        ),
    ]
