# Generated by Django 6.0.1 on 2026-03-02 21:50
# Manually edited to include data migration for document_type conversion.

import django.db.models.deletion
from django.db import migrations, models


def convert_document_types_forward(apps, schema_editor):
    """Convert old JSA/SWP/SOP types to new type system with tags."""
    ProcessDocument = apps.get_model("job", "ProcessDocument")

    mapping = {
        "jsa": {"document_type": "procedure", "tags": ["safety", "jsa"]},
        "swp": {"document_type": "procedure", "tags": ["safety", "swp"]},
        "sop": {"document_type": "procedure", "tags": ["sop"]},
    }

    for old_type, new_values in mapping.items():
        ProcessDocument.objects.filter(document_type=old_type).update(
            document_type=new_values["document_type"],
            tags=new_values["tags"],
            status="active",
        )


def convert_document_types_reverse(apps, schema_editor):
    """Reverse: convert new types back to old JSA/SWP/SOP types (best-effort)."""
    ProcessDocument = apps.get_model("job", "ProcessDocument")

    # Procedures tagged with "jsa" -> jsa
    for doc in ProcessDocument.objects.filter(document_type="procedure"):
        tags = doc.tags or []
        if "jsa" in tags:
            doc.document_type = "jsa"
            doc.tags = []
            doc.save(update_fields=["document_type", "tags"])

    # Procedures tagged with "swp" -> swp, with "sop" -> sop
    for doc in ProcessDocument.objects.filter(document_type="procedure"):
        tags = doc.tags or []
        if "swp" in tags:
            doc.document_type = "swp"
            doc.tags = []
            doc.save(update_fields=["document_type", "tags"])
        elif "sop" in tags:
            doc.document_type = "sop"
            doc.tags = []
            doc.save(update_fields=["document_type", "tags"])


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0070_rename_safetydocument_to_processdocument"),
    ]

    operations = [
        # Step 1: Add new fields
        migrations.AddField(
            model_name="processdocument",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a template that can be filled in to create records",
            ),
        ),
        migrations.AddField(
            model_name="processdocument",
            name="parent_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this record was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_records",
                to="job.processdocument",
            ),
        ),
        migrations.AddField(
            model_name="processdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Document lifecycle status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="processdocument",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Free-text tags, e.g. ["safety", "machinery", "sop"]',
            ),
        ),
        # Step 2: Widen max_length to 20 (keeping old choices so old values are still valid)
        migrations.AlterField(
            model_name="processdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("jsa", "Job Safety Analysis"),
                    ("swp", "Safe Work Procedure"),
                    ("sop", "Standard Operating Procedure"),
                    ("procedure", "Procedure"),
                    ("form", "Form"),
                    ("register", "Register"),
                    ("reference", "Reference"),
                ],
                help_text="Document type: procedure, form, register, or reference",
                max_length=20,
            ),
        ),
        # Step 3: Data migration - convert old types to new types
        migrations.RunPython(
            convert_document_types_forward,
            convert_document_types_reverse,
        ),
        # Step 4: Set final choices (old types no longer valid)
        migrations.AlterField(
            model_name="processdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("procedure", "Procedure"),
                    ("form", "Form"),
                    ("register", "Register"),
                    ("reference", "Reference"),
                ],
                help_text="Document type: procedure, form, register, or reference",
                max_length=20,
            ),
        ),
    ]
