# Generated by Django 6.0.1 on 2026-03-02 22:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0071_expand_process_document_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessDocumentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(help_text="Date this entry relates to"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Entry data - schema varies by document type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Parent process document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="job.processdocument",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Document Entry",
                "verbose_name_plural": "Process Document Entries",
                "db_table": "workflow_processdocumententry",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
    ]
