# Generated by Django 6.0.1 on 2026-03-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0073_add_form_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="processdocumententry",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Soft delete flag - inactive entries are hidden from normal queries",
            ),
        ),
    ]
