# Generated by Django 5.2 on 2025-09-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoting", "0012_supplierproduct_last_scraped"),
    ]

    operations = [
        migrations.AddField(
            model_name="productparsingmapping",
            name="derived_key",
            field=models.CharField(
                blank=True,
                help_text="Derived key for this mapping, if applicable",
                max_length=100,
                null=True,
            ),
        ),
    ]
