# Generated by Django 5.2 on 2025-10-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoting", "0013_productparsingmapping_derived_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparsingmapping",
            name="llm_response",
            field=models.JSONField(
                blank=True, help_text="Full LLM response for debugging", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productparsingmapping",
            name="parser_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
