# Generated by Django 5.2 on 2025-11-15 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoting", "0014_make_parser_fields_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparsingmapping",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who validated this mapping",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
