# Generated by Django 5.2 on 2025-11-15 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0009_clientcontact_unique_client_contact_name"),
        ("quoting", "0015_protect_critical_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapejob",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrape_jobs",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpricelist",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_lists",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scraped_products",
                to="client.client",
            ),
        ),
    ]
