# Generated by Django 6.0.1 on 2026-02-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0016_protect_supplier_relationships"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="is_discontinued",
            field=models.BooleanField(
                default=False,
                help_text="Product URL no longer in supplier sitemap; skip future scrapes",
            ),
        ),
    ]
