# Generated by Django 6.0.1 on 2026-02-14 06:58

from django.db import migrations


def mark_404_products_discontinued(apps, schema_editor):
    """Mark existing 'Page Not Found' junk records as discontinued."""
    SupplierProduct = apps.get_model("quoting", "SupplierProduct")
    marked = SupplierProduct.objects.filter(product_name="Page Not Found").update(
        is_discontinued=True
    )
    if marked:
        print(f"  Marked {marked} 'Page Not Found' products as discontinued")


def reverse_mark(apps, schema_editor):
    """Reverse: unmark all 'Page Not Found' products."""
    SupplierProduct = apps.get_model("quoting", "SupplierProduct")
    SupplierProduct.objects.filter(
        product_name="Page Not Found", is_discontinued=True
    ).update(is_discontinued=False)


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0017_add_is_discontinued_to_supplierproduct"),
    ]

    operations = [
        migrations.RunPython(mark_404_products_discontinued, reverse_mark),
    ]
