# This file is autogenerated by update_init.py script

from .apps import AccountsConfig

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .admin import StaffAdmin
        from .forms import StaffChangeForm, StaffCreationForm
        from .managers import StaffManager
        from .models import Staff
        from .permissions import IsStaff
        from .serializers import (
            CustomTokenObtainPairSerializer,
            KanbanStaffSerializer,
            StaffSerializer,
            UserProfileSerializer,
        )
        from .utils import get_excluded_staff, is_valid_uuid
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AccountsConfig",
    "CustomTokenObtainPairSerializer",
    "IsStaff",
    "KanbanStaffSerializer",
    "Staff",
    "StaffAdmin",
    "StaffChangeForm",
    "StaffCreationForm",
    "StaffManager",
    "StaffSerializer",
    "UserProfileSerializer",
    "get_excluded_staff",
    "is_valid_uuid",
]
