# Generated by Django 5.1.5 on 2025-02-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0067_jobfile_status"),
        ("workflow", "0068_purchase_created_at_purchase_updated_at_and_more"),
    ]

    operations = []
