# Generated by Django 5.1.5 on 2025-02-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0069_merge_20250206_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfile",
            name="print_on_jobsheet",
            field=models.BooleanField(default=False),
        ),
    ]
