# This file is autogenerated by update_init.py script

from .delivery_receipt import DeliveryReceiptCreateView, DeliveryReceiptListView
from .product_mapping import product_mapping_validation, validate_mapping
from .purchase_order import (
    PurchaseOrderCreateView,
    PurchaseOrderEmailView,
    PurchaseOrderListView,
    PurchaseOrderPDFView,
    autosave_purchase_order_view,
    delete_purchase_order_view,
    extract_supplier_quote_data_view,
)
from .purchasing_rest_views import (
    AllJobsAPIView,
    DeliveryReceiptRestView,
    PurchaseOrderAllocationsAPIView,
    PurchaseOrderDetailRestView,
    PurchaseOrderListCreateRestView,
    PurchasingJobsAPIView,
    StockConsumeRestView,
    StockDeactivateRestView,
    StockListRestView,
    XeroItemList,
)
from .stock import (
    consume_stock_api_view,
    create_stock_api_view,
    deactivate_stock_api_view,
    search_available_stock_api,
    use_stock_view,
)

__all__ = [
    "DeliveryReceiptListView",
    "DeliveryReceiptCreateView",
    "product_mapping_validation",
    "validate_mapping",
    "PurchaseOrderListView",
    "PurchaseOrderCreateView",
    "PurchaseOrderEmailView",
    "PurchaseOrderPDFView",
    "autosave_purchase_order_view",
    "delete_purchase_order_view",
    "extract_supplier_quote_data_view",
    "AllJobsAPIView",
    "PurchasingJobsAPIView",
    "XeroItemList",
    "PurchaseOrderListCreateRestView",
    "PurchaseOrderDetailRestView",
    "DeliveryReceiptRestView",
    "StockListRestView",
    "StockDeactivateRestView",
    "StockConsumeRestView",
    "PurchaseOrderAllocationsAPIView",
    "use_stock_view",
    "consume_stock_api_view",
    "create_stock_api_view",
    "search_available_stock_api",
    "deactivate_stock_api_view",
]
