# This file is autogenerated by update_init.py script

from .purchasing_rest_views import (
    AllJobsAPIView,
    AllocationDeleteAPIView,
    AllocationDetailsAPIView,
    DeliveryReceiptRestView,
    ProductMappingListView,
    ProductMappingValidateView,
    PurchaseOrderAllocationsAPIView,
    PurchaseOrderDetailRestView,
    PurchaseOrderETagMixin,
    PurchaseOrderEmailView,
    PurchaseOrderEventListCreateView,
    PurchaseOrderListCreateRestView,
    PurchaseOrderPDFView,
    PurchasingJobsAPIView,
    SupplierPriceStatusAPIView,
    XeroItemList,
)

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .stock_viewset import StockViewSet
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "AllJobsAPIView",
    "AllocationDeleteAPIView",
    "AllocationDetailsAPIView",
    "DeliveryReceiptRestView",
    "ProductMappingListView",
    "ProductMappingValidateView",
    "PurchaseOrderAllocationsAPIView",
    "PurchaseOrderDetailRestView",
    "PurchaseOrderETagMixin",
    "PurchaseOrderEmailView",
    "PurchaseOrderEventListCreateView",
    "PurchaseOrderListCreateRestView",
    "PurchaseOrderPDFView",
    "PurchasingJobsAPIView",
    "StockViewSet",
    "SupplierPriceStatusAPIView",
    "XeroItemList",
]
