# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .daily_timesheet_serializers import (
            DailyTimesheetSummarySerializer,
            DailyTotalsSerializer,
            JobBreakdownSerializer,
            StaffDailyDataSerializer,
            SummaryStatsSerializer,
            TimesheetErrorResponseSerializer,
        )
        from .modern_timesheet_serializers import (
            JobMetricsSerializer,
            JobsListResponseSerializer,
            ModernStaffSerializer,
            ModernTimesheetJobSerializer,
            PaidAbsenceRequestSerializer,
            StaffListResponseSerializer,
            WeeklyStaffDataSerializer,
            WeeklyStaffDataWeeklyHoursSerializer,
            WeeklySummarySerializer,
            WeeklyTimesheetDataSerializer,
        )
        from .payroll_serializers import (
            CreatePayRunRequestSerializer,
            CreatePayRunResponseSerializer,
            PostWeekToXeroRequestSerializer,
            PostWeekToXeroResponseSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CreatePayRunRequestSerializer",
    "CreatePayRunResponseSerializer",
    "DailyTimesheetSummarySerializer",
    "DailyTotalsSerializer",
    "JobBreakdownSerializer",
    "JobMetricsSerializer",
    "JobsListResponseSerializer",
    "ModernStaffSerializer",
    "ModernTimesheetJobSerializer",
    "PaidAbsenceRequestSerializer",
    "PostWeekToXeroRequestSerializer",
    "PostWeekToXeroResponseSerializer",
    "StaffDailyDataSerializer",
    "StaffListResponseSerializer",
    "SummaryStatsSerializer",
    "TimesheetErrorResponseSerializer",
    "WeeklyStaffDataSerializer",
    "WeeklyStaffDataWeeklyHoursSerializer",
    "WeeklySummarySerializer",
    "WeeklyTimesheetDataSerializer",
]
