# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .daily_timesheet_serializers import (
            DailyTimesheetSummarySerializer,
            DailyTotalsSerializer,
            JobBreakdownSerializer,
            StaffDailyDataSerializer,
            SummaryStatsSerializer,
            TimesheetErrorResponseSerializer,
        )
        from .modern_timesheet_serializers import (
            JobMetricsSerializer,
            JobsListResponseSerializer,
            ModernStaffSerializer,
            ModernTimesheetJobSerializer,
            PaidAbsenceSerializer,
            StaffListResponseSerializer,
            WeeklyStaffDataSerializer,
            WeeklyStaffDataWeeklyHoursSerializer,
            WeeklySummarySerializer,
            WeeklyTimesheetDataSerializer,
            WorkshopTimesheetEntryRequestSerializer,
            WorkshopTimesheetEntrySerializer,
            WorkshopTimesheetEntryUpdateSerializer,
            WorkshopTimesheetListResponseSerializer,
            WorkshopTimesheetSummarySerializer,
        )
        from .payroll_serializers import (
            CreatePayRunResponseSerializer,
            CreatePayRunSerializer,
            PayRunDetailsSerializer,
            PayRunForWeekResponseSerializer,
            PayRunSyncResponseSerializer,
            PostWeekToXeroResponseSerializer,
            PostWeekToXeroSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CreatePayRunResponseSerializer",
    "CreatePayRunSerializer",
    "DailyTimesheetSummarySerializer",
    "DailyTotalsSerializer",
    "JobBreakdownSerializer",
    "JobMetricsSerializer",
    "JobsListResponseSerializer",
    "ModernStaffSerializer",
    "ModernTimesheetJobSerializer",
    "PaidAbsenceSerializer",
    "PayRunDetailsSerializer",
    "PayRunForWeekResponseSerializer",
    "PayRunSyncResponseSerializer",
    "PostWeekToXeroResponseSerializer",
    "PostWeekToXeroSerializer",
    "StaffDailyDataSerializer",
    "StaffListResponseSerializer",
    "SummaryStatsSerializer",
    "TimesheetErrorResponseSerializer",
    "WeeklyStaffDataSerializer",
    "WeeklyStaffDataWeeklyHoursSerializer",
    "WeeklySummarySerializer",
    "WeeklyTimesheetDataSerializer",
    "WorkshopTimesheetEntryRequestSerializer",
    "WorkshopTimesheetEntrySerializer",
    "WorkshopTimesheetEntryUpdateSerializer",
    "WorkshopTimesheetListResponseSerializer",
    "WorkshopTimesheetSummarySerializer",
]
