# This file is autogenerated by update_init.py script

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps
    if apps.ready:
        from .daily_timesheet_serializers import (
            JobBreakdownSerializer,
            StaffDailyDataSerializer,
            DailyTotalsSerializer,
            SummaryStatsSerializer,
            DailyTimesheetSummarySerializer,
            TimesheetErrorResponseSerializer,
        )
        from .modern_timesheet_serializers import (
            ModernTimesheetJobSerializer,
            ModernStaffSerializer,
            WeeklyTimesheetDataSerializer,
            PaidAbsenceRequestSerializer,
            StaffListResponseSerializer,
            JobsListResponseSerializer,
        )
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "DailyTimesheetSummarySerializer",
    "DailyTotalsSerializer",
    "JobBreakdownSerializer",
    "JobsListResponseSerializer",
    "ModernStaffSerializer",
    "ModernTimesheetJobSerializer",
    "PaidAbsenceRequestSerializer",
    "StaffDailyDataSerializer",
    "StaffListResponseSerializer",
    "SummaryStatsSerializer",
    "TimesheetErrorResponseSerializer",
    "WeeklyTimesheetDataSerializer",
]
