# Generated by Django 5.2 on 2025-06-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_remove_entry_job_pricing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="latest_estimate_pricing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The latest JobPricing instance representing the estimate for this job, containing its associated parts.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="latest_quote_pricing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The latest JobPricing instance representing the quote for this job, containing its associated parts.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="latest_reality_pricing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The latest JobPricing instance representing the reality (actual) pricing for this job, containing its associated parts.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="archived_pricings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Historical JobPricing instances for this job, preserving past estimates, quotes, or realities.",
                related_name="archived_pricings_for_job",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="latest_estimate_pricing",
            field=models.OneToOneField(
                help_text="The latest JobPricing instance representing the estimate for this job, containing its associated parts.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_estimate_for_job",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="latest_quote_pricing",
            field=models.OneToOneField(
                help_text="The latest JobPricing instance representing the quote for this job, containing its associated parts.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_quote_for_job",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="latest_reality_pricing",
            field=models.OneToOneField(
                help_text="The latest JobPricing instance representing the reality (actual) pricing for this job, containing its associated parts.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_reality_for_job",
                to="job.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="default_part",
            field=models.OneToOneField(
                blank=True,
                help_text="The default 'Main Work' part associated with this JobPricing instance. This part typically holds general time and material entries for the given pricing type.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_job_pricing",
                to="job.part",
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="is_historical",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this JobPricing instance is a historical record, not the latest active one.",
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="job",
            field=models.ForeignKey(
                help_text="The Job to which this pricing instance (collection of parts) belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_pricings",
                to="job.job",
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("estimate", "Estimate"),
                    ("quote", "Quote"),
                    ("reality", "Reality"),
                ],
                default="estimate",
                help_text="The type of pricing this instance represents (estimate, quote, or reality).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="revision_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Tracks the revision number for this specific pricing type.",
            ),
        ),
    ]
