# This file is autogenerated by update_init.py script

from .utils import format_period_label

# Conditional imports (only when Django is ready)
try:
    from django.apps import apps

    if apps.ready:
        from .job_movement import JobMovementMetricsView
        from .payroll_reconciliation import (
            PayrollDateRangeView,
            PayrollReconciliationReport,
        )
        from .pnl import CompanyProfitAndLossReport
except (ImportError, RuntimeError):
    # Django not ready or circular import, skip conditional imports
    pass

__all__ = [
    "CompanyProfitAndLossReport",
    "JobMovementMetricsView",
    "PayrollDateRangeView",
    "PayrollReconciliationReport",
    "format_period_label",
]
